# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class OneDashboardAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :name, T::String
    attribute :page, T::Array.of(T::Hash)
    attribute? :description, T::String.optional
    attribute? :permissions, T::String.optional
    attribute? :variable, T::Array.of(T::Hash).optional
  end
end
