# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_alert_muting_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicAlertMutingRule
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_alert_muting_rule,
      attributes_class: Newrelic::Types::AlertMutingRuleAttributes,
      outputs: { id: :id },
      map: [:condition, :name],
      map_present: [:description, :schedule],
      map_bool: [:enabled]
  end
  module Newrelic
    include NewrelicAlertMutingRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
