# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class AlertMutingRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :condition, T::Array.of(T::Hash)
    attribute :enabled, T::Bool
    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :schedule, T::Array.of(T::Hash).optional
  end
end
