# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_synthetics_multilocation_alert_condition/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicSyntheticsMultilocationAlertCondition
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_synthetics_multilocation_alert_condition,
      attributes_class: Newrelic::Types::SyntheticsMultilocationAlertConditionAttributes,
      outputs: { id: :id },
      map: [:critical, :entities, :name, :policy_id],
      map_present: [:runbook_url, :violation_time_limit_seconds, :warning],
      map_bool: [:enabled]
  end
  module Newrelic
    include NewrelicSyntheticsMultilocationAlertCondition
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
