# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class SyntheticsMultilocationAlertConditionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :critical, T::Array.of(T::Hash)
    attribute :entities, T::Array.of(T::String)
    attribute :name, T::String
    attribute :policy_id, T::Float
    attribute? :enabled, T::Bool.optional
    attribute? :runbook_url, T::String.optional
    attribute? :violation_time_limit_seconds, T::Float.optional
    attribute? :warning, T::Array.of(T::Hash).optional
  end
end
