# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_application_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicApplicationSettings
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_application_settings,
      attributes_class: Newrelic::Types::ApplicationSettingsAttributes,
      outputs: { id: :id },
      map_present: [:app_apdex_threshold, :end_user_apdex_threshold, :error_collector, :tracer_type, :transaction_tracer],
      map_bool: [:enable_real_user_monitoring, :enable_slow_sql, :enable_thread_profiler, :use_server_side_config]
  end
  module Newrelic
    include NewrelicApplicationSettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
