# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class ApplicationSettingsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute? :app_apdex_threshold, T::Float.optional
    attribute? :enable_real_user_monitoring, T::Bool.optional
    attribute? :enable_slow_sql, T::Bool.optional
    attribute? :enable_thread_profiler, T::Bool.optional
    attribute? :end_user_apdex_threshold, T::Float.optional
    attribute? :error_collector, T::Array.of(T::Hash).optional
    attribute? :tracer_type, T::String.optional
    attribute? :transaction_tracer, T::Array.of(T::Hash).optional
    attribute? :use_server_side_config, T::Bool.optional
  end
end
