# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_obfuscation_expression/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicObfuscationExpression
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_obfuscation_expression,
      attributes_class: Newrelic::Types::ObfuscationExpressionAttributes,
      outputs: { id: :id },
      map: [:name, :regex],
      map_present: [:description]
  end
  module Newrelic
    include NewrelicObfuscationExpression
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
