# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_synthetics_secure_credential/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicSyntheticsSecureCredential
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_synthetics_secure_credential,
      attributes_class: Newrelic::Types::SyntheticsSecureCredentialAttributes,
      outputs: { id: :id },
      map: [:key, :value],
      map_present: [:description]
  end
  module Newrelic
    include NewrelicSyntheticsSecureCredential
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
