# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_nrql_alert_condition/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicNrqlAlertCondition
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_nrql_alert_condition,
      attributes_class: Newrelic::Types::NrqlAlertConditionAttributes,
      outputs: { id: :id },
      map: [:name, :nrql, :policy_id],
      map_present: [:aggregation_delay, :aggregation_method, :aggregation_timer, :baseline_direction, :critical, :description, :evaluation_delay, :expiration_duration, :fill_option, :fill_value, :outlier_configuration, :runbook_url, :signal_seasonality, :slide_by, :target_entity, :term, :title_template, :type, :violation_time_limit_seconds, :warning],
      map_bool: [:close_violations_on_expiration, :enabled, :ignore_on_expected_termination, :open_violation_on_expiration]
  end
  module Newrelic
    include NewrelicNrqlAlertCondition
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
