# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class NrqlAlertConditionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :name, T::String
    attribute :nrql, T::Array.of(T::Hash)
    attribute :policy_id, T::Float
    attribute? :aggregation_delay, T::String.optional
    attribute? :aggregation_method, T::String.optional
    attribute? :aggregation_timer, T::String.optional
    attribute? :baseline_direction, T::String.optional
    attribute? :close_violations_on_expiration, T::Bool.optional
    attribute? :critical, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :enabled, T::Bool.optional
    attribute? :evaluation_delay, T::Float.optional
    attribute? :expiration_duration, T::Float.optional
    attribute? :fill_option, T::String.optional
    attribute? :fill_value, T::Float.optional
    attribute? :ignore_on_expected_termination, T::Bool.optional
    attribute? :open_violation_on_expiration, T::Bool.optional
    attribute? :outlier_configuration, T::Array.of(T::Hash).optional
    attribute? :runbook_url, T::String.optional
    attribute? :signal_seasonality, T::String.optional
    attribute? :slide_by, T::Float.optional
    attribute? :target_entity, T::String.optional
    attribute? :term, T::Array.of(T::Hash).optional
    attribute? :title_template, T::String.optional
    attribute? :type, T::String.optional
    attribute? :violation_time_limit_seconds, T::Float.optional
    attribute? :warning, T::Array.of(T::Hash).optional
  end
end
