# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_infra_alert_condition/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicInfraAlertCondition
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_infra_alert_condition,
      attributes_class: Newrelic::Types::InfraAlertConditionAttributes,
      outputs: { id: :id },
      map: [:name, :policy_id, :type],
      map_present: [:comparison, :critical, :description, :integration_provider, :process_where, :runbook_url, :select, :violation_close_timer, :warning, :where],
      map_bool: [:enabled]
  end
  module Newrelic
    include NewrelicInfraAlertCondition
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
