# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class InfraAlertConditionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :name, T::String
    attribute :policy_id, T::Float
    attribute :type, T::String
    attribute? :comparison, T::String.optional
    attribute? :critical, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :enabled, T::Bool.optional
    attribute? :integration_provider, T::String.optional
    attribute? :process_where, T::String.optional
    attribute? :runbook_url, T::String.optional
    attribute? :select, T::String.optional
    attribute? :violation_close_timer, T::Float.optional
    attribute? :warning, T::Array.of(T::Hash).optional
    attribute? :where, T::String.optional
  end
end
