# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_events_to_metrics_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicEventsToMetricsRule
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_events_to_metrics_rule,
      attributes_class: Newrelic::Types::EventsToMetricsRuleAttributes,
      outputs: { id: :id },
      map: [:name, :nrql],
      map_present: [:description],
      map_bool: [:enabled]
  end
  module Newrelic
    include NewrelicEventsToMetricsRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
