# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_cloud_aws_integrations/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicCloudAwsIntegrations
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_cloud_aws_integrations,
      attributes_class: Newrelic::Types::CloudAwsIntegrationsAttributes,
      outputs: { id: :id },
      map: [:linked_account_id],
      map_present: [:alb, :api_gateway, :auto_scaling, :aws_app_sync, :aws_athena, :aws_auto_discovery, :aws_cognito, :aws_connect, :aws_direct_connect, :aws_fsx, :aws_glue, :aws_kinesis_analytics, :aws_media_convert, :aws_media_package_vod, :aws_mq, :aws_msk, :aws_neptune, :aws_qldb, :aws_route53resolver, :aws_states, :aws_transit_gateway, :aws_waf, :aws_wafv2, :billing, :cloudfront, :cloudtrail, :doc_db, :dynamodb, :ebs, :ec2, :ecs, :efs, :elasticache, :elasticbeanstalk, :elasticsearch, :elb, :emr, :health, :iam, :iot, :kinesis, :kinesis_firehose, :lambda, :rds, :redshift, :route53, :s3, :security_hub, :ses, :sns, :sqs, :trusted_advisor, :vpc, :x_ray]
  end
  module Newrelic
    include NewrelicCloudAwsIntegrations
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
