# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_entity_tags/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicEntityTags
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_entity_tags,
      attributes_class: Newrelic::Types::EntityTagsAttributes,
      outputs: { id: :id },
      map: [:guid, :tag]
  end
  module Newrelic
    include NewrelicEntityTags
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
