# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_nrql_drop_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicNrqlDropRule
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_nrql_drop_rule,
      attributes_class: Newrelic::Types::NrqlDropRuleAttributes,
      outputs: { id: :id },
      map: [:action, :nrql],
      map_present: [:description]
  end
  module Newrelic
    include NewrelicNrqlDropRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
