# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_one_dashboard_raw/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicOneDashboardRaw
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_one_dashboard_raw,
      attributes_class: Newrelic::Types::OneDashboardRawAttributes,
      outputs: { id: :id },
      map: [:name, :page],
      map_present: [:description, :permissions]
  end
  module Newrelic
    include NewrelicOneDashboardRaw
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
