# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_synthetics_broken_links_monitor/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicSyntheticsBrokenLinksMonitor
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_synthetics_broken_links_monitor,
      attributes_class: Newrelic::Types::SyntheticsBrokenLinksMonitorAttributes,
      outputs: { id: :id },
      map: [:name, :period, :status, :uri],
      map_present: [:locations_private, :locations_public, :runtime_type, :runtime_type_version, :tag],
      map_bool: [:use_unsupported_legacy_runtime]
  end
  module Newrelic
    include NewrelicSyntheticsBrokenLinksMonitor
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
