# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_workflow/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicWorkflow
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_workflow,
      attributes_class: Newrelic::Types::WorkflowAttributes,
      outputs: { id: :id },
      map: [:destination, :issues_filter, :muting_rules_handling, :name],
      map_present: [:enrichments],
      map_bool: [:destinations_enabled, :enabled, :enrichments_enabled]
  end
  module Newrelic
    include NewrelicWorkflow
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
