# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_cloud_gcp_integrations/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicCloudGcpIntegrations
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_cloud_gcp_integrations,
      attributes_class: Newrelic::Types::CloudGcpIntegrationsAttributes,
      outputs: { id: :id },
      map: [:linked_account_id],
      map_present: [:alloy_db, :app_engine, :big_query, :big_table, :composer, :data_flow, :data_proc, :data_store, :fire_base_database, :fire_base_hosting, :fire_base_storage, :fire_store, :functions, :interconnect, :kubernetes, :load_balancing, :mem_cache, :pub_sub, :redis, :router, :run, :spanner, :sql, :storage, :virtual_machines, :vpc_access]
  end
  module Newrelic
    include NewrelicCloudGcpIntegrations
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
