# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class CloudGcpIntegrationsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :linked_account_id, T::Float
    attribute? :alloy_db, T::Array.of(T::Hash).optional
    attribute? :app_engine, T::Array.of(T::Hash).optional
    attribute? :big_query, T::Array.of(T::Hash).optional
    attribute? :big_table, T::Array.of(T::Hash).optional
    attribute? :composer, T::Array.of(T::Hash).optional
    attribute? :data_flow, T::Array.of(T::Hash).optional
    attribute? :data_proc, T::Array.of(T::Hash).optional
    attribute? :data_store, T::Array.of(T::Hash).optional
    attribute? :fire_base_database, T::Array.of(T::Hash).optional
    attribute? :fire_base_hosting, T::Array.of(T::Hash).optional
    attribute? :fire_base_storage, T::Array.of(T::Hash).optional
    attribute? :fire_store, T::Array.of(T::Hash).optional
    attribute? :functions, T::Array.of(T::Hash).optional
    attribute? :interconnect, T::Array.of(T::Hash).optional
    attribute? :kubernetes, T::Array.of(T::Hash).optional
    attribute? :load_balancing, T::Array.of(T::Hash).optional
    attribute? :mem_cache, T::Array.of(T::Hash).optional
    attribute? :pub_sub, T::Array.of(T::Hash).optional
    attribute? :redis, T::Array.of(T::Hash).optional
    attribute? :router, T::Array.of(T::Hash).optional
    attribute? :run, T::Array.of(T::Hash).optional
    attribute? :spanner, T::Array.of(T::Hash).optional
    attribute? :sql, T::Array.of(T::Hash).optional
    attribute? :storage, T::Array.of(T::Hash).optional
    attribute? :virtual_machines, T::Array.of(T::Hash).optional
    attribute? :vpc_access, T::Array.of(T::Hash).optional
  end
end
