# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_cloud_aws_link_account/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicCloudAwsLinkAccount
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_cloud_aws_link_account,
      attributes_class: Newrelic::Types::CloudAwsLinkAccountAttributes,
      outputs: { id: :id },
      map: [:arn, :name],
      map_present: [:metric_collection_mode]
  end
  module Newrelic
    include NewrelicCloudAwsLinkAccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
