# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_account_management/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicAccountManagement
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_account_management,
      attributes_class: Newrelic::Types::AccountManagementAttributes,
      outputs: { id: :id },
      map: [:name, :region]
  end
  module Newrelic
    include NewrelicAccountManagement
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
