# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class AccountManagementAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :name, T::String
    attribute :region, T::String
  end
end
