# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_group/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicGroup
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_group,
      attributes_class: Newrelic::Types::GroupAttributes,
      outputs: { id: :id },
      map: [:authentication_domain_id, :name],
      map_present: [:user_ids]
  end
  module Newrelic
    include NewrelicGroup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
