# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_synthetics_monitor/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicSyntheticsMonitor
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_synthetics_monitor,
      attributes_class: Newrelic::Types::SyntheticsMonitorAttributes,
      outputs: { id: :id },
      map: [:name, :status, :type],
      map_present: [:browsers, :custom_header, :device_orientation, :device_type, :devices, :locations_private, :locations_public, :runtime_type, :runtime_type_version, :script_language, :tag, :uri, :validation_string],
      map_bool: [:bypass_head_request, :enable_screenshot_on_failure_and_script, :treat_redirect_as_failure, :use_unsupported_legacy_runtime, :verify_ssl]
  end
  module Newrelic
    include NewrelicSyntheticsMonitor
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
