# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class SyntheticsMonitorAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :name, T::String
    attribute :status, T::String
    attribute :type, T::String
    attribute? :browsers, T::Array.of(T::String).optional
    attribute? :bypass_head_request, T::Bool.optional
    attribute? :custom_header, T::Array.of(T::Hash).optional
    attribute? :device_orientation, T::String.optional
    attribute? :device_type, T::String.optional
    attribute? :devices, T::Array.of(T::String).optional
    attribute? :enable_screenshot_on_failure_and_script, T::Bool.optional
    attribute? :locations_private, T::Array.of(T::String).optional
    attribute? :locations_public, T::Array.of(T::String).optional
    attribute? :runtime_type, T::String.optional
    attribute? :runtime_type_version, T::String.optional
    attribute? :script_language, T::String.optional
    attribute? :tag, T::Array.of(T::Hash).optional
    attribute? :treat_redirect_as_failure, T::Bool.optional
    attribute? :uri, T::String.optional
    attribute? :use_unsupported_legacy_runtime, T::Bool.optional
    attribute? :validation_string, T::String.optional
    attribute? :verify_ssl, T::Bool.optional
  end
end
