# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class NotificationChannelAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :destination_id, T::String
    attribute :name, T::String
    attribute :product, T::String
    attribute :property, T::Array.of(T::Hash)
    attribute :type, T::String
    attribute? :active, T::Bool.optional
  end
end
