# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_cloud_oci_link_account/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicCloudOciLinkAccount
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_cloud_oci_link_account,
      attributes_class: Newrelic::Types::CloudOciLinkAccountAttributes,
      outputs: { id: :id },
      map: [:compartment_ocid, :name, :oci_client_id, :oci_client_secret, :oci_domain_url, :oci_home_region, :tenant_id],
      map_present: [:ingest_vault_ocid, :instrumentation_type, :logging_stack_ocid, :metric_stack_ocid, :oci_region, :user_vault_ocid]
  end
  module Newrelic
    include NewrelicCloudOciLinkAccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
