# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class CloudOciLinkAccountAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :compartment_ocid, T::String
    attribute :name, T::String
    attribute :oci_client_id, T::String
    attribute :oci_client_secret, T::String
    attribute :oci_domain_url, T::String
    attribute :oci_home_region, T::String
    attribute :tenant_id, T::String
    attribute? :ingest_vault_ocid, T::String.optional
    attribute? :instrumentation_type, T::String.optional
    attribute? :logging_stack_ocid, T::String.optional
    attribute? :metric_stack_ocid, T::String.optional
    attribute? :oci_region, T::String.optional
    attribute? :user_vault_ocid, T::String.optional
  end
end
