# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_service_level/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicServiceLevel
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_service_level,
      attributes_class: Newrelic::Types::ServiceLevelAttributes,
      outputs: { id: :id },
      map: [:events, :guid, :name, :objective],
      map_present: [:description]
  end
  module Newrelic
    include NewrelicServiceLevel
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
