# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class ServiceLevelAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :events, T::Array.of(T::Hash)
    attribute :guid, T::String
    attribute :name, T::String
    attribute :objective, T::Array.of(T::Hash)
    attribute? :description, T::String.optional
  end
end
