# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_cloud_azure_link_account/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicCloudAzureLinkAccount
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_cloud_azure_link_account,
      attributes_class: Newrelic::Types::CloudAzureLinkAccountAttributes,
      outputs: { id: :id },
      map: [:application_id, :client_secret, :name, :subscription_id, :tenant_id]
  end
  module Newrelic
    include NewrelicCloudAzureLinkAccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
