# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_cloud_aws_eu_sovereign_integrations/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicCloudAwsEuSovereignIntegrations
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_cloud_aws_eu_sovereign_integrations,
      attributes_class: Newrelic::Types::CloudAwsEuSovereignIntegrationsAttributes,
      outputs: { id: :id },
      map: [:linked_account_id],
      map_present: [:billing, :cloudtrail, :x_ray]
  end
  module Newrelic
    include NewrelicCloudAwsEuSovereignIntegrations
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
