# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class CloudAwsEuSovereignIntegrationsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :linked_account_id, T::Float
    attribute? :billing, T::Array.of(T::Hash).optional
    attribute? :cloudtrail, T::Array.of(T::Hash).optional
    attribute? :x_ray, T::Array.of(T::Hash).optional
  end
end
