# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_synthetics_step_monitor/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicSyntheticsStepMonitor
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_synthetics_step_monitor,
      attributes_class: Newrelic::Types::SyntheticsStepMonitorAttributes,
      outputs: { id: :id },
      map: [:name, :period, :status, :steps],
      map_present: [:browsers, :devices, :location_private, :locations_public, :runtime_type, :runtime_type_version, :tag],
      map_bool: [:enable_screenshot_on_failure_and_script, :use_unsupported_legacy_runtime]
  end
  module Newrelic
    include NewrelicSyntheticsStepMonitor
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
