# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class SyntheticsStepMonitorAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :name, T::String
    attribute :period, T::String
    attribute :status, T::String
    attribute :steps, T::Array.of(T::Hash)
    attribute? :browsers, T::Array.of(T::String).optional
    attribute? :devices, T::Array.of(T::String).optional
    attribute? :enable_screenshot_on_failure_and_script, T::Bool.optional
    attribute? :location_private, T::Array.of(T::Hash).optional
    attribute? :locations_public, T::Array.of(T::String).optional
    attribute? :runtime_type, T::String.optional
    attribute? :runtime_type_version, T::String.optional
    attribute? :tag, T::Array.of(T::Hash).optional
    attribute? :use_unsupported_legacy_runtime, T::Bool.optional
  end
end
