# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_alert_policy_channel/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicAlertPolicyChannel
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_alert_policy_channel,
      attributes_class: Newrelic::Types::AlertPolicyChannelAttributes,
      outputs: { id: :id },
      map: [:channel_ids, :policy_id]
  end
  module Newrelic
    include NewrelicAlertPolicyChannel
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
