# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class ObfuscationRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :action, T::Array.of(T::Hash)
    attribute :enabled, T::Bool
    attribute :filter, T::String
    attribute :name, T::String
    attribute? :description, T::String.optional
  end
end
