# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_monitor_downtime/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicMonitorDowntime
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_monitor_downtime,
      attributes_class: Newrelic::Types::MonitorDowntimeAttributes,
      outputs: { id: :id },
      map: [:end_time, :mode, :name, :start_time, :time_zone],
      map_present: [:end_repeat, :frequency, :maintenance_days, :monitor_guids]
  end
  module Newrelic
    include NewrelicMonitorDowntime
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
