# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_cloud_aws_govcloud_integrations/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicCloudAwsGovcloudIntegrations
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_cloud_aws_govcloud_integrations,
      attributes_class: Newrelic::Types::CloudAwsGovcloudIntegrationsAttributes,
      outputs: { id: :id },
      map: [:linked_account_id],
      map_present: [:alb, :api_gateway, :auto_scaling, :aws_direct_connect, :aws_states, :cloudtrail, :dynamo_db, :ebs, :ec2, :elastic_search, :elb, :emr, :iam, :lambda, :rds, :red_shift, :route53, :s3, :sns, :sqs]
  end
  module Newrelic
    include NewrelicCloudAwsGovcloudIntegrations
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
