# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_alert_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicAlertPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_alert_policy,
      attributes_class: Newrelic::Types::AlertPolicyAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:channel_ids, :incident_preference]
  end
  module Newrelic
    include NewrelicAlertPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
