# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class AlertPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :name, T::String
    attribute? :channel_ids, T::Array.of(T::Float).optional
    attribute? :incident_preference, T::String.optional
  end
end
