# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_workload/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicWorkload
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_workload,
      attributes_class: Newrelic::Types::WorkloadAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :entity_search_query, :status_config_automatic, :status_config_static]
  end
  module Newrelic
    include NewrelicWorkload
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
