# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class WorkloadAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :name, T::String
    attribute? :description, T::String.optional
    attribute? :entity_search_query, T::Array.of(T::Hash).optional
    attribute? :status_config_automatic, T::Array.of(T::Hash).optional
    attribute? :status_config_static, T::Array.of(T::Hash).optional
  end
end
