# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_synthetics_alert_condition/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicSyntheticsAlertCondition
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_synthetics_alert_condition,
      attributes_class: Newrelic::Types::SyntheticsAlertConditionAttributes,
      outputs: { id: :id },
      map: [:monitor_id, :name, :policy_id],
      map_present: [:runbook_url],
      map_bool: [:enabled]
  end
  module Newrelic
    include NewrelicSyntheticsAlertCondition
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
