# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class SyntheticsAlertConditionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :monitor_id, T::String
    attribute :name, T::String
    attribute :policy_id, T::Float
    attribute? :enabled, T::Bool.optional
    attribute? :runbook_url, T::String.optional
  end
end
