# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_api_access_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicApiAccessKey
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_api_access_key,
      attributes_class: Newrelic::Types::ApiAccessKeyAttributes,
      outputs: { id: :id },
      map: [:key_type],
      map_present: [:account_id]
  end
  module Newrelic
    include NewrelicApiAccessKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
