# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_cloud_azure_integrations/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicCloudAzureIntegrations
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_cloud_azure_integrations,
      attributes_class: Newrelic::Types::CloudAzureIntegrationsAttributes,
      outputs: { id: :id },
      map: [:linked_account_id],
      map_present: [:api_management, :app_gateway, :app_service, :auto_discovery, :containers, :cosmos_db, :cost_management, :data_factory, :event_hub, :express_route, :firewalls, :front_door, :functions, :key_vault, :load_balancer, :logic_apps, :machine_learning, :maria_db, :monitor, :mysql, :mysql_flexible, :postgresql, :postgresql_flexible, :power_bi_dedicated, :redis_cache, :service_bus, :sql, :sql_managed, :storage, :virtual_machine, :virtual_networks, :vms, :vpn_gateway]
  end
  module Newrelic
    include NewrelicCloudAzureIntegrations
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
