# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class CloudAzureIntegrationsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :linked_account_id, T::Float
    attribute? :api_management, T::Array.of(T::Hash).optional
    attribute? :app_gateway, T::Array.of(T::Hash).optional
    attribute? :app_service, T::Array.of(T::Hash).optional
    attribute? :auto_discovery, T::Array.of(T::Hash).optional
    attribute? :containers, T::Array.of(T::Hash).optional
    attribute? :cosmos_db, T::Array.of(T::Hash).optional
    attribute? :cost_management, T::Array.of(T::Hash).optional
    attribute? :data_factory, T::Array.of(T::Hash).optional
    attribute? :event_hub, T::Array.of(T::Hash).optional
    attribute? :express_route, T::Array.of(T::Hash).optional
    attribute? :firewalls, T::Array.of(T::Hash).optional
    attribute? :front_door, T::Array.of(T::Hash).optional
    attribute? :functions, T::Array.of(T::Hash).optional
    attribute? :key_vault, T::Array.of(T::Hash).optional
    attribute? :load_balancer, T::Array.of(T::Hash).optional
    attribute? :logic_apps, T::Array.of(T::Hash).optional
    attribute? :machine_learning, T::Array.of(T::Hash).optional
    attribute? :maria_db, T::Array.of(T::Hash).optional
    attribute? :monitor, T::Array.of(T::Hash).optional
    attribute? :mysql, T::Array.of(T::Hash).optional
    attribute? :mysql_flexible, T::Array.of(T::Hash).optional
    attribute? :postgresql, T::Array.of(T::Hash).optional
    attribute? :postgresql_flexible, T::Array.of(T::Hash).optional
    attribute? :power_bi_dedicated, T::Array.of(T::Hash).optional
    attribute? :redis_cache, T::Array.of(T::Hash).optional
    attribute? :service_bus, T::Array.of(T::Hash).optional
    attribute? :sql, T::Array.of(T::Hash).optional
    attribute? :sql_managed, T::Array.of(T::Hash).optional
    attribute? :storage, T::Array.of(T::Hash).optional
    attribute? :virtual_machine, T::Array.of(T::Hash).optional
    attribute? :virtual_networks, T::Array.of(T::Hash).optional
    attribute? :vms, T::Array.of(T::Hash).optional
    attribute? :vpn_gateway, T::Array.of(T::Hash).optional
  end
end
