# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class AlertConditionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :entities, T::Array.of(T::Float)
    attribute :metric, T::String
    attribute :name, T::String
    attribute :policy_id, T::Float
    attribute :term, T::Array.of(T::Hash)
    attribute :type, T::String
    attribute? :condition_scope, T::String.optional
    attribute? :enabled, T::Bool.optional
    attribute? :gc_metric, T::String.optional
    attribute? :runbook_url, T::String.optional
    attribute? :user_defined_metric, T::String.optional
    attribute? :user_defined_value_function, T::String.optional
    attribute? :violation_close_timer, T::Float.optional
  end
end
