# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_insights_event/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicInsightsEvent
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_insights_event,
      attributes_class: Newrelic::Types::InsightsEventAttributes,
      outputs: { id: :id },
      map: [:event]
  end
  module Newrelic
    include NewrelicInsightsEvent
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
