# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class SyntheticsPrivateLocationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :description, T::String
    attribute :name, T::String
    attribute? :verified_script_execution, T::Bool.optional
  end
end
