# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_log_parsing_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicLogParsingRule
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_log_parsing_rule,
      attributes_class: Newrelic::Types::LogParsingRuleAttributes,
      outputs: { id: :id },
      map: [:grok, :lucene, :name, :nrql],
      map_present: [:attribute],
      map_bool: [:enabled]
  end
  module Newrelic
    include NewrelicLogParsingRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
