# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class LogParsingRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :enabled, T::Bool
    attribute :grok, T::String
    attribute :lucene, T::String
    attribute :name, T::String
    attribute :nrql, T::String
    attribute? :attribute, T::String.optional
  end
end
