# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class AlertCompoundConditionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :component_conditions, T::Array.of(T::Hash)
    attribute :enabled, T::Bool
    attribute :name, T::String
    attribute :policy_id, T::Float
    attribute :trigger_expression, T::String
    attribute? :runbook_url, T::String.optional
  end
end
