# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_alert_channel/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicAlertChannel
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_alert_channel,
      attributes_class: Newrelic::Types::AlertChannelAttributes,
      outputs: { id: :id },
      map: [:name, :type],
      map_present: [:config]
  end
  module Newrelic
    include NewrelicAlertChannel
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
