# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_notification_destination/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicNotificationDestination
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_notification_destination,
      attributes_class: Newrelic::Types::NotificationDestinationAttributes,
      outputs: { id: :id },
      map: [:name, :property, :type],
      map_present: [:auth_basic, :auth_custom_header, :auth_token, :secure_url],
      map_bool: [:active]
  end
  module Newrelic
    include NewrelicNotificationDestination
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
