# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_data_partition_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicDataPartitionRule
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_data_partition_rule,
      attributes_class: Newrelic::Types::DataPartitionRuleAttributes,
      outputs: { id: :id },
      map: [:nrql, :retention_policy, :target_data_partition],
      map_present: [:description],
      map_bool: [:enabled]
  end
  module Newrelic
    include NewrelicDataPartitionRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
