# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class UserAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :authentication_domain_id, T::String
    attribute :email_id, T::String
    attribute :name, T::String
    attribute? :user_type, T::String.optional
  end
end
