# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_pipeline_cloud_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicPipelineCloudRule
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_pipeline_cloud_rule,
      attributes_class: Newrelic::Types::PipelineCloudRuleAttributes,
      outputs: { id: :id },
      map: [:name, :nrql],
      map_present: [:description]
  end
  module Newrelic
    include NewrelicPipelineCloudRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
