# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/newrelic_key_transaction/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module NewrelicKeyTransaction
    include Pangea::Resources::ResourceBuilder

    define_resource :newrelic_key_transaction,
      attributes_class: Newrelic::Types::KeyTransactionAttributes,
      outputs: { id: :id },
      map: [:apdex_index, :application_guid, :browser_apdex_target, :metric_name, :name]
  end
  module Newrelic
    include NewrelicKeyTransaction
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Newrelic)
