# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Newrelic::Types
  include Dry.Types()

  class KeyTransactionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Newrelic::Types

    attribute :apdex_index, T::Float
    attribute :application_guid, T::String
    attribute :browser_apdex_target, T::Float
    attribute :metric_name, T::String
    attribute :name, T::String
  end
end
