# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_synthetics_private_location resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicSyntheticsPrivateLocation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { description: 'test-value', name: 'test-value' } }

  describe ':newrelic_synthetics_private_location' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_private_location('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_synthetics_private_location', 'test')
        validate_required_attributes(config, [:description, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_private_location('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_synthetics_private_location)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_private_location('test', required_attrs)

        expect(ref.id).to eq("${newrelic_synthetics_private_location.test.id}")
        expect(ref.account_id).to eq("${newrelic_synthetics_private_location.test.account_id}")
        expect(ref.domain_id).to eq("${newrelic_synthetics_private_location.test.domain_id}")
        expect(ref.guid).to eq("${newrelic_synthetics_private_location.test.guid}")
        expect(ref.key).to eq("${newrelic_synthetics_private_location.test.key}")
        expect(ref.location_id).to eq("${newrelic_synthetics_private_location.test.location_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_private_location('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_private_location', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('domain_id')
        expect(config).not_to have_key('guid')
        expect(config).not_to have_key('key')
        expect(config).not_to have_key('location_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ verified_script_execution: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_private_location('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_private_location', 'full')
        expect(config).to have_key('verified_script_execution')
      end
    end

    context 'optional attributes' do
      it 'includes verified_script_execution when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_private_location('opt', required_attrs.merge(verified_script_execution: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_private_location', 'opt')
        expect(config).to have_key('verified_script_execution')
      end

      it 'omits verified_script_execution when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_private_location('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_private_location', 'minimal')
        expect(config).not_to have_key('verified_script_execution')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts verified_script_execution=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(verified_script_execution: val)
          synth.newrelic_synthetics_private_location("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_synthetics_private_location', "bool_#{val}")
          expect(config['verified_script_execution']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_private_location('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_private_location', 'typed')
        expect(config['description']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_private_location('first', required_attrs)
        synth.newrelic_synthetics_private_location('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_synthetics_private_location')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_synthetics_private_location,
    method: :newrelic_synthetics_private_location,
    required_attrs: { description: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :account_id, :domain_id, :guid, :key, :location_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:verified_script_execution]
end
