# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_synthetics_step_monitor resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicSyntheticsStepMonitor do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', period: 'test-value', status: 'test-value', steps: [{ 'key1' => 'val1' }] } }

  describe ':newrelic_synthetics_step_monitor' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'test')
        validate_required_attributes(config, [:name, :period, :status, :steps])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_step_monitor('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_synthetics_step_monitor)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_step_monitor('test', required_attrs)

        expect(ref.id).to eq("${newrelic_synthetics_step_monitor.test.id}")
        expect(ref.account_id).to eq("${newrelic_synthetics_step_monitor.test.account_id}")
        expect(ref.guid).to eq("${newrelic_synthetics_step_monitor.test.guid}")
        expect(ref.monitor_id).to eq("${newrelic_synthetics_step_monitor.test.monitor_id}")
        expect(ref.period_in_minutes).to eq("${newrelic_synthetics_step_monitor.test.period_in_minutes}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('guid')
        expect(config).not_to have_key('monitor_id')
        expect(config).not_to have_key('period_in_minutes')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ browsers: ['test-value'], devices: ['test-value'], enable_screenshot_on_failure_and_script: true, location_private: [{ 'key1' => 'val1' }], locations_public: ['test-value'], runtime_type: 'test-value', runtime_type_version: 'test-value', tag: [{ 'key1' => 'val1' }], use_unsupported_legacy_runtime: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'full')
        expect(config).to have_key('browsers')
        expect(config).to have_key('devices')
        expect(config).to have_key('enable_screenshot_on_failure_and_script')
        expect(config).to have_key('location_private')
        expect(config).to have_key('locations_public')
        expect(config).to have_key('runtime_type')
        expect(config).to have_key('runtime_type_version')
        expect(config).to have_key('tag')
        expect(config).to have_key('use_unsupported_legacy_runtime')
      end
    end

    context 'optional attributes' do
      it 'includes browsers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('opt', required_attrs.merge(browsers: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'opt')
        expect(config).to have_key('browsers')
      end

      it 'omits browsers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'minimal')
        expect(config).not_to have_key('browsers')
      end
      it 'includes devices when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('opt', required_attrs.merge(devices: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'opt')
        expect(config).to have_key('devices')
      end

      it 'omits devices when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'minimal')
        expect(config).not_to have_key('devices')
      end
      it 'includes enable_screenshot_on_failure_and_script when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('opt', required_attrs.merge(enable_screenshot_on_failure_and_script: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'opt')
        expect(config).to have_key('enable_screenshot_on_failure_and_script')
      end

      it 'omits enable_screenshot_on_failure_and_script when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'minimal')
        expect(config).not_to have_key('enable_screenshot_on_failure_and_script')
      end
      it 'includes location_private when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('opt', required_attrs.merge(location_private: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'opt')
        expect(config).to have_key('location_private')
      end

      it 'omits location_private when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'minimal')
        expect(config).not_to have_key('location_private')
      end
      it 'includes locations_public when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('opt', required_attrs.merge(locations_public: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'opt')
        expect(config).to have_key('locations_public')
      end

      it 'omits locations_public when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'minimal')
        expect(config).not_to have_key('locations_public')
      end
      it 'includes runtime_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('opt', required_attrs.merge(runtime_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'opt')
        expect(config).to have_key('runtime_type')
      end

      it 'omits runtime_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'minimal')
        expect(config).not_to have_key('runtime_type')
      end
      it 'includes runtime_type_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('opt', required_attrs.merge(runtime_type_version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'opt')
        expect(config).to have_key('runtime_type_version')
      end

      it 'omits runtime_type_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'minimal')
        expect(config).not_to have_key('runtime_type_version')
      end
      it 'includes tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('opt', required_attrs.merge(tag: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'opt')
        expect(config).to have_key('tag')
      end

      it 'omits tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'minimal')
        expect(config).not_to have_key('tag')
      end
      it 'includes use_unsupported_legacy_runtime when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('opt', required_attrs.merge(use_unsupported_legacy_runtime: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'opt')
        expect(config).to have_key('use_unsupported_legacy_runtime')
      end

      it 'omits use_unsupported_legacy_runtime when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'minimal')
        expect(config).not_to have_key('use_unsupported_legacy_runtime')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enable_screenshot_on_failure_and_script=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_screenshot_on_failure_and_script: val)
          synth.newrelic_synthetics_step_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', "bool_#{val}")
          expect(config['enable_screenshot_on_failure_and_script']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts use_unsupported_legacy_runtime=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(use_unsupported_legacy_runtime: val)
          synth.newrelic_synthetics_step_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', "bool_#{val}")
          expect(config['use_unsupported_legacy_runtime']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_step_monitor', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['period']).to be_a(String)
        expect(config['status']).to be_a(String)
        expect(config['steps']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_step_monitor('first', required_attrs)
        synth.newrelic_synthetics_step_monitor('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_synthetics_step_monitor')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_synthetics_step_monitor,
    method: :newrelic_synthetics_step_monitor,
    required_attrs: { name: 'test-value', period: 'test-value', status: 'test-value', steps: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :account_id, :guid, :monitor_id, :period_in_minutes],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enable_screenshot_on_failure_and_script, :use_unsupported_legacy_runtime]
end
