# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_cloud_aws_integrations resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicCloudAwsIntegrations do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { linked_account_id: 3.14 } }

  describe ':newrelic_cloud_aws_integrations' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'test')
        validate_required_attributes(config, [:linked_account_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_cloud_aws_integrations('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_cloud_aws_integrations)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_cloud_aws_integrations('test', required_attrs)

        expect(ref.id).to eq("${newrelic_cloud_aws_integrations.test.id}")
        expect(ref.account_id).to eq("${newrelic_cloud_aws_integrations.test.account_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'test')
        expect(config).not_to have_key('account_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alb: [{ 'key1' => 'val1' }], api_gateway: [{ 'key1' => 'val1' }], auto_scaling: [{ 'key1' => 'val1' }], aws_app_sync: [{ 'key1' => 'val1' }], aws_athena: [{ 'key1' => 'val1' }], aws_auto_discovery: [{ 'key1' => 'val1' }], aws_cognito: [{ 'key1' => 'val1' }], aws_connect: [{ 'key1' => 'val1' }], aws_direct_connect: [{ 'key1' => 'val1' }], aws_fsx: [{ 'key1' => 'val1' }], aws_glue: [{ 'key1' => 'val1' }], aws_kinesis_analytics: [{ 'key1' => 'val1' }], aws_media_convert: [{ 'key1' => 'val1' }], aws_media_package_vod: [{ 'key1' => 'val1' }], aws_mq: [{ 'key1' => 'val1' }], aws_msk: [{ 'key1' => 'val1' }], aws_neptune: [{ 'key1' => 'val1' }], aws_qldb: [{ 'key1' => 'val1' }], aws_route53resolver: [{ 'key1' => 'val1' }], aws_states: [{ 'key1' => 'val1' }], aws_transit_gateway: [{ 'key1' => 'val1' }], aws_waf: [{ 'key1' => 'val1' }], aws_wafv2: [{ 'key1' => 'val1' }], billing: [{ 'key1' => 'val1' }], cloudfront: [{ 'key1' => 'val1' }], cloudtrail: [{ 'key1' => 'val1' }], doc_db: [{ 'key1' => 'val1' }], dynamodb: [{ 'key1' => 'val1' }], ebs: [{ 'key1' => 'val1' }], ec2: [{ 'key1' => 'val1' }], ecs: [{ 'key1' => 'val1' }], efs: [{ 'key1' => 'val1' }], elasticache: [{ 'key1' => 'val1' }], elasticbeanstalk: [{ 'key1' => 'val1' }], elasticsearch: [{ 'key1' => 'val1' }], elb: [{ 'key1' => 'val1' }], emr: [{ 'key1' => 'val1' }], health: [{ 'key1' => 'val1' }], iam: [{ 'key1' => 'val1' }], iot: [{ 'key1' => 'val1' }], kinesis: [{ 'key1' => 'val1' }], kinesis_firehose: [{ 'key1' => 'val1' }], lambda: [{ 'key1' => 'val1' }], rds: [{ 'key1' => 'val1' }], redshift: [{ 'key1' => 'val1' }], route53: [{ 'key1' => 'val1' }], s3: [{ 'key1' => 'val1' }], security_hub: [{ 'key1' => 'val1' }], ses: [{ 'key1' => 'val1' }], sns: [{ 'key1' => 'val1' }], sqs: [{ 'key1' => 'val1' }], trusted_advisor: [{ 'key1' => 'val1' }], vpc: [{ 'key1' => 'val1' }], x_ray: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'full')
        expect(config).to have_key('alb')
        expect(config).to have_key('api_gateway')
        expect(config).to have_key('auto_scaling')
        expect(config).to have_key('aws_app_sync')
        expect(config).to have_key('aws_athena')
        expect(config).to have_key('aws_auto_discovery')
        expect(config).to have_key('aws_cognito')
        expect(config).to have_key('aws_connect')
        expect(config).to have_key('aws_direct_connect')
        expect(config).to have_key('aws_fsx')
        expect(config).to have_key('aws_glue')
        expect(config).to have_key('aws_kinesis_analytics')
        expect(config).to have_key('aws_media_convert')
        expect(config).to have_key('aws_media_package_vod')
        expect(config).to have_key('aws_mq')
        expect(config).to have_key('aws_msk')
        expect(config).to have_key('aws_neptune')
        expect(config).to have_key('aws_qldb')
        expect(config).to have_key('aws_route53resolver')
        expect(config).to have_key('aws_states')
        expect(config).to have_key('aws_transit_gateway')
        expect(config).to have_key('aws_waf')
        expect(config).to have_key('aws_wafv2')
        expect(config).to have_key('billing')
        expect(config).to have_key('cloudfront')
        expect(config).to have_key('cloudtrail')
        expect(config).to have_key('doc_db')
        expect(config).to have_key('dynamodb')
        expect(config).to have_key('ebs')
        expect(config).to have_key('ec2')
        expect(config).to have_key('ecs')
        expect(config).to have_key('efs')
        expect(config).to have_key('elasticache')
        expect(config).to have_key('elasticbeanstalk')
        expect(config).to have_key('elasticsearch')
        expect(config).to have_key('elb')
        expect(config).to have_key('emr')
        expect(config).to have_key('health')
        expect(config).to have_key('iam')
        expect(config).to have_key('iot')
        expect(config).to have_key('kinesis')
        expect(config).to have_key('kinesis_firehose')
        expect(config).to have_key('lambda')
        expect(config).to have_key('rds')
        expect(config).to have_key('redshift')
        expect(config).to have_key('route53')
        expect(config).to have_key('s3')
        expect(config).to have_key('security_hub')
        expect(config).to have_key('ses')
        expect(config).to have_key('sns')
        expect(config).to have_key('sqs')
        expect(config).to have_key('trusted_advisor')
        expect(config).to have_key('vpc')
        expect(config).to have_key('x_ray')
      end
    end

    context 'optional attributes' do
      it 'includes alb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(alb: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('alb')
      end

      it 'omits alb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('alb')
      end
      it 'includes api_gateway when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(api_gateway: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('api_gateway')
      end

      it 'omits api_gateway when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('api_gateway')
      end
      it 'includes auto_scaling when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(auto_scaling: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('auto_scaling')
      end

      it 'omits auto_scaling when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('auto_scaling')
      end
      it 'includes aws_app_sync when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_app_sync: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_app_sync')
      end

      it 'omits aws_app_sync when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_app_sync')
      end
      it 'includes aws_athena when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_athena: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_athena')
      end

      it 'omits aws_athena when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_athena')
      end
      it 'includes aws_auto_discovery when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_auto_discovery: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_auto_discovery')
      end

      it 'omits aws_auto_discovery when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_auto_discovery')
      end
      it 'includes aws_cognito when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_cognito: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_cognito')
      end

      it 'omits aws_cognito when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_cognito')
      end
      it 'includes aws_connect when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_connect: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_connect')
      end

      it 'omits aws_connect when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_connect')
      end
      it 'includes aws_direct_connect when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_direct_connect: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_direct_connect')
      end

      it 'omits aws_direct_connect when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_direct_connect')
      end
      it 'includes aws_fsx when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_fsx: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_fsx')
      end

      it 'omits aws_fsx when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_fsx')
      end
      it 'includes aws_glue when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_glue: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_glue')
      end

      it 'omits aws_glue when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_glue')
      end
      it 'includes aws_kinesis_analytics when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_kinesis_analytics: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_kinesis_analytics')
      end

      it 'omits aws_kinesis_analytics when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_kinesis_analytics')
      end
      it 'includes aws_media_convert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_media_convert: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_media_convert')
      end

      it 'omits aws_media_convert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_media_convert')
      end
      it 'includes aws_media_package_vod when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_media_package_vod: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_media_package_vod')
      end

      it 'omits aws_media_package_vod when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_media_package_vod')
      end
      it 'includes aws_mq when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_mq: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_mq')
      end

      it 'omits aws_mq when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_mq')
      end
      it 'includes aws_msk when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_msk: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_msk')
      end

      it 'omits aws_msk when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_msk')
      end
      it 'includes aws_neptune when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_neptune: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_neptune')
      end

      it 'omits aws_neptune when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_neptune')
      end
      it 'includes aws_qldb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_qldb: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_qldb')
      end

      it 'omits aws_qldb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_qldb')
      end
      it 'includes aws_route53resolver when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_route53resolver: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_route53resolver')
      end

      it 'omits aws_route53resolver when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_route53resolver')
      end
      it 'includes aws_states when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_states: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_states')
      end

      it 'omits aws_states when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_states')
      end
      it 'includes aws_transit_gateway when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_transit_gateway: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_transit_gateway')
      end

      it 'omits aws_transit_gateway when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_transit_gateway')
      end
      it 'includes aws_waf when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_waf: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_waf')
      end

      it 'omits aws_waf when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_waf')
      end
      it 'includes aws_wafv2 when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(aws_wafv2: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('aws_wafv2')
      end

      it 'omits aws_wafv2 when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('aws_wafv2')
      end
      it 'includes billing when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(billing: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('billing')
      end

      it 'omits billing when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('billing')
      end
      it 'includes cloudfront when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(cloudfront: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('cloudfront')
      end

      it 'omits cloudfront when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('cloudfront')
      end
      it 'includes cloudtrail when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(cloudtrail: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('cloudtrail')
      end

      it 'omits cloudtrail when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('cloudtrail')
      end
      it 'includes doc_db when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(doc_db: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('doc_db')
      end

      it 'omits doc_db when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('doc_db')
      end
      it 'includes dynamodb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(dynamodb: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('dynamodb')
      end

      it 'omits dynamodb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('dynamodb')
      end
      it 'includes ebs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(ebs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('ebs')
      end

      it 'omits ebs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('ebs')
      end
      it 'includes ec2 when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(ec2: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('ec2')
      end

      it 'omits ec2 when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('ec2')
      end
      it 'includes ecs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(ecs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('ecs')
      end

      it 'omits ecs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('ecs')
      end
      it 'includes efs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(efs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('efs')
      end

      it 'omits efs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('efs')
      end
      it 'includes elasticache when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(elasticache: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('elasticache')
      end

      it 'omits elasticache when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('elasticache')
      end
      it 'includes elasticbeanstalk when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(elasticbeanstalk: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('elasticbeanstalk')
      end

      it 'omits elasticbeanstalk when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('elasticbeanstalk')
      end
      it 'includes elasticsearch when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(elasticsearch: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('elasticsearch')
      end

      it 'omits elasticsearch when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('elasticsearch')
      end
      it 'includes elb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(elb: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('elb')
      end

      it 'omits elb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('elb')
      end
      it 'includes emr when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(emr: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('emr')
      end

      it 'omits emr when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('emr')
      end
      it 'includes health when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(health: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('health')
      end

      it 'omits health when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('health')
      end
      it 'includes iam when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(iam: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('iam')
      end

      it 'omits iam when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('iam')
      end
      it 'includes iot when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(iot: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('iot')
      end

      it 'omits iot when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('iot')
      end
      it 'includes kinesis when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(kinesis: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('kinesis')
      end

      it 'omits kinesis when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('kinesis')
      end
      it 'includes kinesis_firehose when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(kinesis_firehose: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('kinesis_firehose')
      end

      it 'omits kinesis_firehose when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('kinesis_firehose')
      end
      it 'includes lambda when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(lambda: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('lambda')
      end

      it 'omits lambda when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('lambda')
      end
      it 'includes rds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(rds: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('rds')
      end

      it 'omits rds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('rds')
      end
      it 'includes redshift when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(redshift: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('redshift')
      end

      it 'omits redshift when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('redshift')
      end
      it 'includes route53 when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(route53: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('route53')
      end

      it 'omits route53 when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('route53')
      end
      it 'includes s3 when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(s3: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('s3')
      end

      it 'omits s3 when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('s3')
      end
      it 'includes security_hub when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(security_hub: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('security_hub')
      end

      it 'omits security_hub when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('security_hub')
      end
      it 'includes ses when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(ses: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('ses')
      end

      it 'omits ses when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('ses')
      end
      it 'includes sns when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(sns: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('sns')
      end

      it 'omits sns when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('sns')
      end
      it 'includes sqs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(sqs: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('sqs')
      end

      it 'omits sqs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('sqs')
      end
      it 'includes trusted_advisor when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(trusted_advisor: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('trusted_advisor')
      end

      it 'omits trusted_advisor when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('trusted_advisor')
      end
      it 'includes vpc when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(vpc: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('vpc')
      end

      it 'omits vpc when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('vpc')
      end
      it 'includes x_ray when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('opt', required_attrs.merge(x_ray: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'opt')
        expect(config).to have_key('x_ray')
      end

      it 'omits x_ray when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'minimal')
        expect(config).not_to have_key('x_ray')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_aws_integrations', 'typed')
        expect(config['linked_account_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_integrations('first', required_attrs)
        synth.newrelic_cloud_aws_integrations('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_cloud_aws_integrations')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_cloud_aws_integrations,
    method: :newrelic_cloud_aws_integrations,
    required_attrs: { linked_account_id: 3.14 },
    expected_outputs: [:id, :account_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
