# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_cloud_azure_integrations resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicCloudAzureIntegrations do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { linked_account_id: 3.14 } }

  describe ':newrelic_cloud_azure_integrations' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'test')
        validate_required_attributes(config, [:linked_account_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_cloud_azure_integrations('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_cloud_azure_integrations)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_cloud_azure_integrations('test', required_attrs)

        expect(ref.id).to eq("${newrelic_cloud_azure_integrations.test.id}")
        expect(ref.account_id).to eq("${newrelic_cloud_azure_integrations.test.account_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'test')
        expect(config).not_to have_key('account_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ api_management: [{ 'key1' => 'val1' }], app_gateway: [{ 'key1' => 'val1' }], app_service: [{ 'key1' => 'val1' }], auto_discovery: [{ 'key1' => 'val1' }], containers: [{ 'key1' => 'val1' }], cosmos_db: [{ 'key1' => 'val1' }], cost_management: [{ 'key1' => 'val1' }], data_factory: [{ 'key1' => 'val1' }], event_hub: [{ 'key1' => 'val1' }], express_route: [{ 'key1' => 'val1' }], firewalls: [{ 'key1' => 'val1' }], front_door: [{ 'key1' => 'val1' }], functions: [{ 'key1' => 'val1' }], key_vault: [{ 'key1' => 'val1' }], load_balancer: [{ 'key1' => 'val1' }], logic_apps: [{ 'key1' => 'val1' }], machine_learning: [{ 'key1' => 'val1' }], maria_db: [{ 'key1' => 'val1' }], monitor: [{ 'key1' => 'val1' }], mysql: [{ 'key1' => 'val1' }], mysql_flexible: [{ 'key1' => 'val1' }], postgresql: [{ 'key1' => 'val1' }], postgresql_flexible: [{ 'key1' => 'val1' }], power_bi_dedicated: [{ 'key1' => 'val1' }], redis_cache: [{ 'key1' => 'val1' }], service_bus: [{ 'key1' => 'val1' }], sql: [{ 'key1' => 'val1' }], sql_managed: [{ 'key1' => 'val1' }], storage: [{ 'key1' => 'val1' }], virtual_machine: [{ 'key1' => 'val1' }], virtual_networks: [{ 'key1' => 'val1' }], vms: [{ 'key1' => 'val1' }], vpn_gateway: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'full')
        expect(config).to have_key('api_management')
        expect(config).to have_key('app_gateway')
        expect(config).to have_key('app_service')
        expect(config).to have_key('auto_discovery')
        expect(config).to have_key('containers')
        expect(config).to have_key('cosmos_db')
        expect(config).to have_key('cost_management')
        expect(config).to have_key('data_factory')
        expect(config).to have_key('event_hub')
        expect(config).to have_key('express_route')
        expect(config).to have_key('firewalls')
        expect(config).to have_key('front_door')
        expect(config).to have_key('functions')
        expect(config).to have_key('key_vault')
        expect(config).to have_key('load_balancer')
        expect(config).to have_key('logic_apps')
        expect(config).to have_key('machine_learning')
        expect(config).to have_key('maria_db')
        expect(config).to have_key('monitor')
        expect(config).to have_key('mysql')
        expect(config).to have_key('mysql_flexible')
        expect(config).to have_key('postgresql')
        expect(config).to have_key('postgresql_flexible')
        expect(config).to have_key('power_bi_dedicated')
        expect(config).to have_key('redis_cache')
        expect(config).to have_key('service_bus')
        expect(config).to have_key('sql')
        expect(config).to have_key('sql_managed')
        expect(config).to have_key('storage')
        expect(config).to have_key('virtual_machine')
        expect(config).to have_key('virtual_networks')
        expect(config).to have_key('vms')
        expect(config).to have_key('vpn_gateway')
      end
    end

    context 'optional attributes' do
      it 'includes api_management when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(api_management: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('api_management')
      end

      it 'omits api_management when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('api_management')
      end
      it 'includes app_gateway when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(app_gateway: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('app_gateway')
      end

      it 'omits app_gateway when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('app_gateway')
      end
      it 'includes app_service when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(app_service: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('app_service')
      end

      it 'omits app_service when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('app_service')
      end
      it 'includes auto_discovery when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(auto_discovery: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('auto_discovery')
      end

      it 'omits auto_discovery when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('auto_discovery')
      end
      it 'includes containers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(containers: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('containers')
      end

      it 'omits containers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('containers')
      end
      it 'includes cosmos_db when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(cosmos_db: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('cosmos_db')
      end

      it 'omits cosmos_db when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('cosmos_db')
      end
      it 'includes cost_management when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(cost_management: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('cost_management')
      end

      it 'omits cost_management when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('cost_management')
      end
      it 'includes data_factory when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(data_factory: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('data_factory')
      end

      it 'omits data_factory when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('data_factory')
      end
      it 'includes event_hub when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(event_hub: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('event_hub')
      end

      it 'omits event_hub when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('event_hub')
      end
      it 'includes express_route when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(express_route: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('express_route')
      end

      it 'omits express_route when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('express_route')
      end
      it 'includes firewalls when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(firewalls: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('firewalls')
      end

      it 'omits firewalls when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('firewalls')
      end
      it 'includes front_door when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(front_door: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('front_door')
      end

      it 'omits front_door when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('front_door')
      end
      it 'includes functions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(functions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('functions')
      end

      it 'omits functions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('functions')
      end
      it 'includes key_vault when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(key_vault: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('key_vault')
      end

      it 'omits key_vault when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('key_vault')
      end
      it 'includes load_balancer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(load_balancer: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('load_balancer')
      end

      it 'omits load_balancer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('load_balancer')
      end
      it 'includes logic_apps when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(logic_apps: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('logic_apps')
      end

      it 'omits logic_apps when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('logic_apps')
      end
      it 'includes machine_learning when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(machine_learning: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('machine_learning')
      end

      it 'omits machine_learning when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('machine_learning')
      end
      it 'includes maria_db when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(maria_db: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('maria_db')
      end

      it 'omits maria_db when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('maria_db')
      end
      it 'includes monitor when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(monitor: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('monitor')
      end

      it 'omits monitor when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('monitor')
      end
      it 'includes mysql when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(mysql: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('mysql')
      end

      it 'omits mysql when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('mysql')
      end
      it 'includes mysql_flexible when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(mysql_flexible: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('mysql_flexible')
      end

      it 'omits mysql_flexible when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('mysql_flexible')
      end
      it 'includes postgresql when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(postgresql: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('postgresql')
      end

      it 'omits postgresql when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('postgresql')
      end
      it 'includes postgresql_flexible when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(postgresql_flexible: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('postgresql_flexible')
      end

      it 'omits postgresql_flexible when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('postgresql_flexible')
      end
      it 'includes power_bi_dedicated when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(power_bi_dedicated: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('power_bi_dedicated')
      end

      it 'omits power_bi_dedicated when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('power_bi_dedicated')
      end
      it 'includes redis_cache when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(redis_cache: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('redis_cache')
      end

      it 'omits redis_cache when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('redis_cache')
      end
      it 'includes service_bus when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(service_bus: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('service_bus')
      end

      it 'omits service_bus when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('service_bus')
      end
      it 'includes sql when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(sql: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('sql')
      end

      it 'omits sql when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('sql')
      end
      it 'includes sql_managed when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(sql_managed: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('sql_managed')
      end

      it 'omits sql_managed when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('sql_managed')
      end
      it 'includes storage when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(storage: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('storage')
      end

      it 'omits storage when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('storage')
      end
      it 'includes virtual_machine when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(virtual_machine: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('virtual_machine')
      end

      it 'omits virtual_machine when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('virtual_machine')
      end
      it 'includes virtual_networks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(virtual_networks: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('virtual_networks')
      end

      it 'omits virtual_networks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('virtual_networks')
      end
      it 'includes vms when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(vms: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('vms')
      end

      it 'omits vms when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('vms')
      end
      it 'includes vpn_gateway when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('opt', required_attrs.merge(vpn_gateway: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'opt')
        expect(config).to have_key('vpn_gateway')
      end

      it 'omits vpn_gateway when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'minimal')
        expect(config).not_to have_key('vpn_gateway')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_azure_integrations', 'typed')
        expect(config['linked_account_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_azure_integrations('first', required_attrs)
        synth.newrelic_cloud_azure_integrations('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_cloud_azure_integrations')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_cloud_azure_integrations,
    method: :newrelic_cloud_azure_integrations,
    required_attrs: { linked_account_id: 3.14 },
    expected_outputs: [:id, :account_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
