# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_cloud_aws_eu_sovereign_integrations resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicCloudAwsEuSovereignIntegrations do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { linked_account_id: 3.14 } }

  describe ':newrelic_cloud_aws_eu_sovereign_integrations' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'test')
        validate_required_attributes(config, [:linked_account_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_cloud_aws_eu_sovereign_integrations('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_cloud_aws_eu_sovereign_integrations)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_cloud_aws_eu_sovereign_integrations('test', required_attrs)

        expect(ref.id).to eq("${newrelic_cloud_aws_eu_sovereign_integrations.test.id}")
        expect(ref.account_id).to eq("${newrelic_cloud_aws_eu_sovereign_integrations.test.account_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'test')
        expect(config).not_to have_key('account_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ billing: [{ 'key1' => 'val1' }], cloudtrail: [{ 'key1' => 'val1' }], x_ray: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'full')
        expect(config).to have_key('billing')
        expect(config).to have_key('cloudtrail')
        expect(config).to have_key('x_ray')
      end
    end

    context 'optional attributes' do
      it 'includes billing when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('opt', required_attrs.merge(billing: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'opt')
        expect(config).to have_key('billing')
      end

      it 'omits billing when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'minimal')
        expect(config).not_to have_key('billing')
      end
      it 'includes cloudtrail when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('opt', required_attrs.merge(cloudtrail: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'opt')
        expect(config).to have_key('cloudtrail')
      end

      it 'omits cloudtrail when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'minimal')
        expect(config).not_to have_key('cloudtrail')
      end
      it 'includes x_ray when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('opt', required_attrs.merge(x_ray: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'opt')
        expect(config).to have_key('x_ray')
      end

      it 'omits x_ray when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'minimal')
        expect(config).not_to have_key('x_ray')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_aws_eu_sovereign_integrations', 'typed')
        expect(config['linked_account_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('first', required_attrs)
        synth.newrelic_cloud_aws_eu_sovereign_integrations('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_cloud_aws_eu_sovereign_integrations')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_cloud_aws_eu_sovereign_integrations,
    method: :newrelic_cloud_aws_eu_sovereign_integrations,
    required_attrs: { linked_account_id: 3.14 },
    expected_outputs: [:id, :account_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
