# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_api_access_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicApiAccessKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { key_type: 'test-value' } }

  describe ':newrelic_api_access_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_api_access_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_api_access_key', 'test')
        validate_required_attributes(config, [:key_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_api_access_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_api_access_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_api_access_key('test', required_attrs)

        expect(ref.id).to eq("${newrelic_api_access_key.test.id}")
        expect(ref.ingest_type).to eq("${newrelic_api_access_key.test.ingest_type}")
        expect(ref.key).to eq("${newrelic_api_access_key.test.key}")
        expect(ref.name).to eq("${newrelic_api_access_key.test.name}")
        expect(ref.notes).to eq("${newrelic_api_access_key.test.notes}")
        expect(ref.user_id).to eq("${newrelic_api_access_key.test.user_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_api_access_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_api_access_key', 'test')
        expect(config).not_to have_key('ingest_type')
        expect(config).not_to have_key('key')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('notes')
        expect(config).not_to have_key('user_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ account_id: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_api_access_key('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_api_access_key', 'full')
        expect(config).to have_key('account_id')
      end
    end

    context 'optional attributes' do
      it 'includes account_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_api_access_key('opt', required_attrs.merge(account_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_api_access_key', 'opt')
        expect(config).to have_key('account_id')
      end

      it 'omits account_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_api_access_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_api_access_key', 'minimal')
        expect(config).not_to have_key('account_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_api_access_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_api_access_key', 'typed')
        expect(config['key_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_api_access_key('first', required_attrs)
        synth.newrelic_api_access_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_api_access_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_api_access_key,
    method: :newrelic_api_access_key,
    required_attrs: { key_type: 'test-value' },
    expected_outputs: [:id, :ingest_type, :key, :name, :notes, :user_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
