# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_synthetics_monitor resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicSyntheticsMonitor do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', status: 'test-value', type: 'test-value' } }

  describe ':newrelic_synthetics_monitor' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'test')
        validate_required_attributes(config, [:name, :status, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_monitor('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_synthetics_monitor)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_monitor('test', required_attrs)

        expect(ref.id).to eq("${newrelic_synthetics_monitor.test.id}")
        expect(ref.account_id).to eq("${newrelic_synthetics_monitor.test.account_id}")
        expect(ref.monitor_id).to eq("${newrelic_synthetics_monitor.test.monitor_id}")
        expect(ref.period).to eq("${newrelic_synthetics_monitor.test.period}")
        expect(ref.period_in_minutes).to eq("${newrelic_synthetics_monitor.test.period_in_minutes}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('monitor_id')
        expect(config).not_to have_key('period')
        expect(config).not_to have_key('period_in_minutes')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ browsers: ['test-value'], bypass_head_request: true, custom_header: [{ 'key1' => 'val1' }], device_orientation: 'test-value', device_type: 'test-value', devices: ['test-value'], enable_screenshot_on_failure_and_script: true, locations_private: ['test-value'], locations_public: ['test-value'], runtime_type: 'test-value', runtime_type_version: 'test-value', script_language: 'test-value', tag: [{ 'key1' => 'val1' }], treat_redirect_as_failure: true, uri: 'test-value', use_unsupported_legacy_runtime: true, validation_string: 'test-value', verify_ssl: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'full')
        expect(config).to have_key('browsers')
        expect(config).to have_key('bypass_head_request')
        expect(config).to have_key('custom_header')
        expect(config).to have_key('device_orientation')
        expect(config).to have_key('device_type')
        expect(config).to have_key('devices')
        expect(config).to have_key('enable_screenshot_on_failure_and_script')
        expect(config).to have_key('locations_private')
        expect(config).to have_key('locations_public')
        expect(config).to have_key('runtime_type')
        expect(config).to have_key('runtime_type_version')
        expect(config).to have_key('script_language')
        expect(config).to have_key('tag')
        expect(config).to have_key('treat_redirect_as_failure')
        expect(config).to have_key('uri')
        expect(config).to have_key('use_unsupported_legacy_runtime')
        expect(config).to have_key('validation_string')
        expect(config).to have_key('verify_ssl')
      end
    end

    context 'optional attributes' do
      it 'includes browsers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(browsers: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('browsers')
      end

      it 'omits browsers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('browsers')
      end
      it 'includes bypass_head_request when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(bypass_head_request: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('bypass_head_request')
      end

      it 'omits bypass_head_request when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('bypass_head_request')
      end
      it 'includes custom_header when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(custom_header: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('custom_header')
      end

      it 'omits custom_header when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('custom_header')
      end
      it 'includes device_orientation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(device_orientation: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('device_orientation')
      end

      it 'omits device_orientation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('device_orientation')
      end
      it 'includes device_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(device_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('device_type')
      end

      it 'omits device_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('device_type')
      end
      it 'includes devices when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(devices: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('devices')
      end

      it 'omits devices when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('devices')
      end
      it 'includes enable_screenshot_on_failure_and_script when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(enable_screenshot_on_failure_and_script: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('enable_screenshot_on_failure_and_script')
      end

      it 'omits enable_screenshot_on_failure_and_script when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('enable_screenshot_on_failure_and_script')
      end
      it 'includes locations_private when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(locations_private: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('locations_private')
      end

      it 'omits locations_private when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('locations_private')
      end
      it 'includes locations_public when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(locations_public: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('locations_public')
      end

      it 'omits locations_public when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('locations_public')
      end
      it 'includes runtime_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(runtime_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('runtime_type')
      end

      it 'omits runtime_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('runtime_type')
      end
      it 'includes runtime_type_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(runtime_type_version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('runtime_type_version')
      end

      it 'omits runtime_type_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('runtime_type_version')
      end
      it 'includes script_language when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(script_language: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('script_language')
      end

      it 'omits script_language when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('script_language')
      end
      it 'includes tag when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(tag: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('tag')
      end

      it 'omits tag when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('tag')
      end
      it 'includes treat_redirect_as_failure when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(treat_redirect_as_failure: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('treat_redirect_as_failure')
      end

      it 'omits treat_redirect_as_failure when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('treat_redirect_as_failure')
      end
      it 'includes uri when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(uri: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('uri')
      end

      it 'omits uri when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('uri')
      end
      it 'includes use_unsupported_legacy_runtime when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(use_unsupported_legacy_runtime: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('use_unsupported_legacy_runtime')
      end

      it 'omits use_unsupported_legacy_runtime when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('use_unsupported_legacy_runtime')
      end
      it 'includes validation_string when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(validation_string: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('validation_string')
      end

      it 'omits validation_string when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('validation_string')
      end
      it 'includes verify_ssl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('opt', required_attrs.merge(verify_ssl: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'opt')
        expect(config).to have_key('verify_ssl')
      end

      it 'omits verify_ssl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'minimal')
        expect(config).not_to have_key('verify_ssl')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts bypass_head_request=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(bypass_head_request: val)
          synth.newrelic_synthetics_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_synthetics_monitor', "bool_#{val}")
          expect(config['bypass_head_request']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_screenshot_on_failure_and_script=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_screenshot_on_failure_and_script: val)
          synth.newrelic_synthetics_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_synthetics_monitor', "bool_#{val}")
          expect(config['enable_screenshot_on_failure_and_script']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts treat_redirect_as_failure=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(treat_redirect_as_failure: val)
          synth.newrelic_synthetics_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_synthetics_monitor', "bool_#{val}")
          expect(config['treat_redirect_as_failure']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts use_unsupported_legacy_runtime=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(use_unsupported_legacy_runtime: val)
          synth.newrelic_synthetics_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_synthetics_monitor', "bool_#{val}")
          expect(config['use_unsupported_legacy_runtime']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts verify_ssl=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(verify_ssl: val)
          synth.newrelic_synthetics_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_synthetics_monitor', "bool_#{val}")
          expect(config['verify_ssl']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_monitor', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['status']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_monitor('first', required_attrs)
        synth.newrelic_synthetics_monitor('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_synthetics_monitor')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_synthetics_monitor,
    method: :newrelic_synthetics_monitor,
    required_attrs: { name: 'test-value', status: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :account_id, :monitor_id, :period, :period_in_minutes],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:bypass_head_request, :enable_screenshot_on_failure_and_script, :treat_redirect_as_failure, :use_unsupported_legacy_runtime, :verify_ssl]
end
