# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_nrql_drop_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicNrqlDropRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { action: 'test-value', nrql: 'test-value' } }

  describe ':newrelic_nrql_drop_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_drop_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_nrql_drop_rule', 'test')
        validate_required_attributes(config, [:action, :nrql])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_nrql_drop_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_nrql_drop_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_nrql_drop_rule('test', required_attrs)

        expect(ref.id).to eq("${newrelic_nrql_drop_rule.test.id}")
        expect(ref.account_id).to eq("${newrelic_nrql_drop_rule.test.account_id}")
        expect(ref.pipeline_cloud_rule_entity_id).to eq("${newrelic_nrql_drop_rule.test.pipeline_cloud_rule_entity_id}")
        expect(ref.rule_id).to eq("${newrelic_nrql_drop_rule.test.rule_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_drop_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_nrql_drop_rule', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('pipeline_cloud_rule_entity_id')
        expect(config).not_to have_key('rule_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_drop_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_nrql_drop_rule', 'full')
        expect(config).to have_key('description')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_drop_rule('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_drop_rule', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_drop_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_drop_rule', 'minimal')
        expect(config).not_to have_key('description')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_drop_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_nrql_drop_rule', 'typed')
        expect(config['action']).to be_a(String)
        expect(config['nrql']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_drop_rule('first', required_attrs)
        synth.newrelic_nrql_drop_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_nrql_drop_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_nrql_drop_rule,
    method: :newrelic_nrql_drop_rule,
    required_attrs: { action: 'test-value', nrql: 'test-value' },
    expected_outputs: [:id, :account_id, :pipeline_cloud_rule_entity_id, :rule_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
