# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_notification_channel resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicNotificationChannel do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { destination_id: 'test-value', name: 'test-value', product: 'test-value', property: [{ 'key1' => 'val1' }], type: 'test-value' } }

  describe ':newrelic_notification_channel' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_notification_channel('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_notification_channel', 'test')
        validate_required_attributes(config, [:destination_id, :name, :product, :property, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_notification_channel('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_notification_channel)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_notification_channel('test', required_attrs)

        expect(ref.id).to eq("${newrelic_notification_channel.test.id}")
        expect(ref.account_id).to eq("${newrelic_notification_channel.test.account_id}")
        expect(ref.status).to eq("${newrelic_notification_channel.test.status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_notification_channel('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_notification_channel', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('status')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ active: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_notification_channel('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_notification_channel', 'full')
        expect(config).to have_key('active')
      end
    end

    context 'optional attributes' do
      it 'includes active when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_notification_channel('opt', required_attrs.merge(active: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_notification_channel', 'opt')
        expect(config).to have_key('active')
      end

      it 'omits active when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_notification_channel('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_notification_channel', 'minimal')
        expect(config).not_to have_key('active')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts active=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(active: val)
          synth.newrelic_notification_channel("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_notification_channel', "bool_#{val}")
          expect(config['active']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_notification_channel('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_notification_channel', 'typed')
        expect(config['destination_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['product']).to be_a(String)
        expect(config['property']).to be_a(Array)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_notification_channel('first', required_attrs)
        synth.newrelic_notification_channel('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_notification_channel')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_notification_channel,
    method: :newrelic_notification_channel,
    required_attrs: { destination_id: 'test-value', name: 'test-value', product: 'test-value', property: [{ 'key1' => 'val1' }], type: 'test-value' },
    expected_outputs: [:id, :account_id, :status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:active]
end
