# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_nrql_alert_condition resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicNrqlAlertCondition do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', nrql: [{ 'key1' => 'val1' }], policy_id: 3.14 } }

  describe ':newrelic_nrql_alert_condition' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'test')
        validate_required_attributes(config, [:name, :nrql, :policy_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_nrql_alert_condition('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_nrql_alert_condition)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_nrql_alert_condition('test', required_attrs)

        expect(ref.id).to eq("${newrelic_nrql_alert_condition.test.id}")
        expect(ref.account_id).to eq("${newrelic_nrql_alert_condition.test.account_id}")
        expect(ref.aggregation_window).to eq("${newrelic_nrql_alert_condition.test.aggregation_window}")
        expect(ref.entity_guid).to eq("${newrelic_nrql_alert_condition.test.entity_guid}")
        expect(ref.violation_time_limit).to eq("${newrelic_nrql_alert_condition.test.violation_time_limit}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('aggregation_window')
        expect(config).not_to have_key('entity_guid')
        expect(config).not_to have_key('violation_time_limit')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ aggregation_delay: 'test-value', aggregation_method: 'test-value', aggregation_timer: 'test-value', baseline_direction: 'test-value', close_violations_on_expiration: true, critical: [{ 'key1' => 'val1' }], description: 'test-value', enabled: true, evaluation_delay: 3.14, expiration_duration: 3.14, fill_option: 'test-value', fill_value: 3.14, ignore_on_expected_termination: true, open_violation_on_expiration: true, outlier_configuration: [{ 'key1' => 'val1' }], runbook_url: 'test-value', signal_seasonality: 'test-value', slide_by: 3.14, target_entity: 'test-value', term: [{ 'key1' => 'val1' }], title_template: 'test-value', type: 'test-value', violation_time_limit_seconds: 3.14, warning: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'full')
        expect(config).to have_key('aggregation_delay')
        expect(config).to have_key('aggregation_method')
        expect(config).to have_key('aggregation_timer')
        expect(config).to have_key('baseline_direction')
        expect(config).to have_key('close_violations_on_expiration')
        expect(config).to have_key('critical')
        expect(config).to have_key('description')
        expect(config).to have_key('enabled')
        expect(config).to have_key('evaluation_delay')
        expect(config).to have_key('expiration_duration')
        expect(config).to have_key('fill_option')
        expect(config).to have_key('fill_value')
        expect(config).to have_key('ignore_on_expected_termination')
        expect(config).to have_key('open_violation_on_expiration')
        expect(config).to have_key('outlier_configuration')
        expect(config).to have_key('runbook_url')
        expect(config).to have_key('signal_seasonality')
        expect(config).to have_key('slide_by')
        expect(config).to have_key('target_entity')
        expect(config).to have_key('term')
        expect(config).to have_key('title_template')
        expect(config).to have_key('type')
        expect(config).to have_key('violation_time_limit_seconds')
        expect(config).to have_key('warning')
      end
    end

    context 'optional attributes' do
      it 'includes aggregation_delay when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(aggregation_delay: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('aggregation_delay')
      end

      it 'omits aggregation_delay when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('aggregation_delay')
      end
      it 'includes aggregation_method when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(aggregation_method: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('aggregation_method')
      end

      it 'omits aggregation_method when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('aggregation_method')
      end
      it 'includes aggregation_timer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(aggregation_timer: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('aggregation_timer')
      end

      it 'omits aggregation_timer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('aggregation_timer')
      end
      it 'includes baseline_direction when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(baseline_direction: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('baseline_direction')
      end

      it 'omits baseline_direction when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('baseline_direction')
      end
      it 'includes close_violations_on_expiration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(close_violations_on_expiration: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('close_violations_on_expiration')
      end

      it 'omits close_violations_on_expiration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('close_violations_on_expiration')
      end
      it 'includes critical when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(critical: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('critical')
      end

      it 'omits critical when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('critical')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes evaluation_delay when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(evaluation_delay: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('evaluation_delay')
      end

      it 'omits evaluation_delay when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('evaluation_delay')
      end
      it 'includes expiration_duration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(expiration_duration: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('expiration_duration')
      end

      it 'omits expiration_duration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('expiration_duration')
      end
      it 'includes fill_option when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(fill_option: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('fill_option')
      end

      it 'omits fill_option when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('fill_option')
      end
      it 'includes fill_value when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(fill_value: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('fill_value')
      end

      it 'omits fill_value when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('fill_value')
      end
      it 'includes ignore_on_expected_termination when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(ignore_on_expected_termination: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('ignore_on_expected_termination')
      end

      it 'omits ignore_on_expected_termination when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('ignore_on_expected_termination')
      end
      it 'includes open_violation_on_expiration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(open_violation_on_expiration: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('open_violation_on_expiration')
      end

      it 'omits open_violation_on_expiration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('open_violation_on_expiration')
      end
      it 'includes outlier_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(outlier_configuration: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('outlier_configuration')
      end

      it 'omits outlier_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('outlier_configuration')
      end
      it 'includes runbook_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(runbook_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('runbook_url')
      end

      it 'omits runbook_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('runbook_url')
      end
      it 'includes signal_seasonality when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(signal_seasonality: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('signal_seasonality')
      end

      it 'omits signal_seasonality when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('signal_seasonality')
      end
      it 'includes slide_by when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(slide_by: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('slide_by')
      end

      it 'omits slide_by when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('slide_by')
      end
      it 'includes target_entity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(target_entity: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('target_entity')
      end

      it 'omits target_entity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('target_entity')
      end
      it 'includes term when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(term: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('term')
      end

      it 'omits term when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('term')
      end
      it 'includes title_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(title_template: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('title_template')
      end

      it 'omits title_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('title_template')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('type')
      end
      it 'includes violation_time_limit_seconds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(violation_time_limit_seconds: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('violation_time_limit_seconds')
      end

      it 'omits violation_time_limit_seconds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('violation_time_limit_seconds')
      end
      it 'includes warning when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('opt', required_attrs.merge(warning: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'opt')
        expect(config).to have_key('warning')
      end

      it 'omits warning when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'minimal')
        expect(config).not_to have_key('warning')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts close_violations_on_expiration=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(close_violations_on_expiration: val)
          synth.newrelic_nrql_alert_condition("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', "bool_#{val}")
          expect(config['close_violations_on_expiration']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.newrelic_nrql_alert_condition("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ignore_on_expected_termination=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_on_expected_termination: val)
          synth.newrelic_nrql_alert_condition("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', "bool_#{val}")
          expect(config['ignore_on_expected_termination']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts open_violation_on_expiration=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(open_violation_on_expiration: val)
          synth.newrelic_nrql_alert_condition("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', "bool_#{val}")
          expect(config['open_violation_on_expiration']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_nrql_alert_condition', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['nrql']).to be_a(Array)
        expect(config['policy_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_nrql_alert_condition('first', required_attrs)
        synth.newrelic_nrql_alert_condition('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_nrql_alert_condition')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_nrql_alert_condition,
    method: :newrelic_nrql_alert_condition,
    required_attrs: { name: 'test-value', nrql: [{ 'key1' => 'val1' }], policy_id: 3.14 },
    expected_outputs: [:id, :account_id, :aggregation_window, :entity_guid, :violation_time_limit],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:close_violations_on_expiration, :enabled, :ignore_on_expected_termination, :open_violation_on_expiration]
end
