# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_one_dashboard_json resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicOneDashboardJson do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { json: 'test-value' } }

  describe ':newrelic_one_dashboard_json' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_json('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_one_dashboard_json', 'test')
        validate_required_attributes(config, [:json])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_one_dashboard_json('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_one_dashboard_json)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_one_dashboard_json('test', required_attrs)

        expect(ref.id).to eq("${newrelic_one_dashboard_json.test.id}")
        expect(ref.account_id).to eq("${newrelic_one_dashboard_json.test.account_id}")
        expect(ref.guid).to eq("${newrelic_one_dashboard_json.test.guid}")
        expect(ref.permalink).to eq("${newrelic_one_dashboard_json.test.permalink}")
        expect(ref.updated_at).to eq("${newrelic_one_dashboard_json.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_json('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_one_dashboard_json', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('guid')
        expect(config).not_to have_key('permalink')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_json('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_one_dashboard_json', 'typed')
        expect(config['json']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_json('first', required_attrs)
        synth.newrelic_one_dashboard_json('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_one_dashboard_json')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_one_dashboard_json,
    method: :newrelic_one_dashboard_json,
    required_attrs: { json: 'test-value' },
    expected_outputs: [:id, :account_id, :guid, :permalink, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
