# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_synthetics_secure_credential resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicSyntheticsSecureCredential do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { key: 'test-value', value: 'test-value' } }

  describe ':newrelic_synthetics_secure_credential' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_secure_credential('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_synthetics_secure_credential', 'test')
        validate_required_attributes(config, [:key, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_secure_credential('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_synthetics_secure_credential)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_secure_credential('test', required_attrs)

        expect(ref.id).to eq("${newrelic_synthetics_secure_credential.test.id}")
        expect(ref.account_id).to eq("${newrelic_synthetics_secure_credential.test.account_id}")
        expect(ref.last_updated).to eq("${newrelic_synthetics_secure_credential.test.last_updated}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_secure_credential('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_secure_credential', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('last_updated')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_secure_credential('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_secure_credential', 'full')
        expect(config).to have_key('description')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_secure_credential('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_secure_credential', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_secure_credential('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_secure_credential', 'minimal')
        expect(config).not_to have_key('description')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:value]
        expect(sensitive_fields).to include(:value)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_secure_credential('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_secure_credential', 'typed')
        expect(config['key']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_secure_credential('first', required_attrs)
        synth.newrelic_synthetics_secure_credential('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_synthetics_secure_credential')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_synthetics_secure_credential,
    method: :newrelic_synthetics_secure_credential,
    required_attrs: { key: 'test-value', value: 'test-value' },
    expected_outputs: [:id, :account_id, :last_updated],
    sensitive_fields: [:value],
    immutable_fields: [],
    boolean_fields: []
end
