# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_workflow resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicWorkflow do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { destination: [{ 'key1' => 'val1' }], issues_filter: [{ 'key1' => 'val1' }], muting_rules_handling: 'test-value', name: 'test-value' } }

  describe ':newrelic_workflow' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_workflow', 'test')
        validate_required_attributes(config, [:destination, :issues_filter, :muting_rules_handling, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_workflow('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_workflow)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_workflow('test', required_attrs)

        expect(ref.id).to eq("${newrelic_workflow.test.id}")
        expect(ref.account_id).to eq("${newrelic_workflow.test.account_id}")
        expect(ref.guid).to eq("${newrelic_workflow.test.guid}")
        expect(ref.last_run).to eq("${newrelic_workflow.test.last_run}")
        expect(ref.workflow_id).to eq("${newrelic_workflow.test.workflow_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_workflow', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('guid')
        expect(config).not_to have_key('last_run')
        expect(config).not_to have_key('workflow_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ destinations_enabled: true, enabled: true, enrichments: [{ 'key1' => 'val1' }], enrichments_enabled: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_workflow', 'full')
        expect(config).to have_key('destinations_enabled')
        expect(config).to have_key('enabled')
        expect(config).to have_key('enrichments')
        expect(config).to have_key('enrichments_enabled')
      end
    end

    context 'optional attributes' do
      it 'includes destinations_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('opt', required_attrs.merge(destinations_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workflow', 'opt')
        expect(config).to have_key('destinations_enabled')
      end

      it 'omits destinations_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workflow', 'minimal')
        expect(config).not_to have_key('destinations_enabled')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workflow', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workflow', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes enrichments when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('opt', required_attrs.merge(enrichments: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workflow', 'opt')
        expect(config).to have_key('enrichments')
      end

      it 'omits enrichments when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workflow', 'minimal')
        expect(config).not_to have_key('enrichments')
      end
      it 'includes enrichments_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('opt', required_attrs.merge(enrichments_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workflow', 'opt')
        expect(config).to have_key('enrichments_enabled')
      end

      it 'omits enrichments_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workflow', 'minimal')
        expect(config).not_to have_key('enrichments_enabled')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts destinations_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(destinations_enabled: val)
          synth.newrelic_workflow("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_workflow', "bool_#{val}")
          expect(config['destinations_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.newrelic_workflow("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_workflow', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enrichments_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enrichments_enabled: val)
          synth.newrelic_workflow("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_workflow', "bool_#{val}")
          expect(config['enrichments_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_workflow', 'typed')
        expect(config['destination']).to be_a(Array)
        expect(config['issues_filter']).to be_a(Array)
        expect(config['muting_rules_handling']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workflow('first', required_attrs)
        synth.newrelic_workflow('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_workflow')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_workflow,
    method: :newrelic_workflow,
    required_attrs: { destination: [{ 'key1' => 'val1' }], issues_filter: [{ 'key1' => 'val1' }], muting_rules_handling: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :account_id, :guid, :last_run, :workflow_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:destinations_enabled, :enabled, :enrichments_enabled]
end
