# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_monitor_downtime resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicMonitorDowntime do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { end_time: 'test-value', mode: 'test-value', name: 'test-value', start_time: 'test-value', time_zone: 'test-value' } }

  describe ':newrelic_monitor_downtime' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'test')
        validate_required_attributes(config, [:end_time, :mode, :name, :start_time, :time_zone])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_monitor_downtime('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_monitor_downtime)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_monitor_downtime('test', required_attrs)

        expect(ref.id).to eq("${newrelic_monitor_downtime.test.id}")
        expect(ref.account_id).to eq("${newrelic_monitor_downtime.test.account_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'test')
        expect(config).not_to have_key('account_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ end_repeat: [{ 'key1' => 'val1' }], frequency: [{ 'key1' => 'val1' }], maintenance_days: ['test-value'], monitor_guids: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'full')
        expect(config).to have_key('end_repeat')
        expect(config).to have_key('frequency')
        expect(config).to have_key('maintenance_days')
        expect(config).to have_key('monitor_guids')
      end
    end

    context 'optional attributes' do
      it 'includes end_repeat when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('opt', required_attrs.merge(end_repeat: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'opt')
        expect(config).to have_key('end_repeat')
      end

      it 'omits end_repeat when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'minimal')
        expect(config).not_to have_key('end_repeat')
      end
      it 'includes frequency when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('opt', required_attrs.merge(frequency: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'opt')
        expect(config).to have_key('frequency')
      end

      it 'omits frequency when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'minimal')
        expect(config).not_to have_key('frequency')
      end
      it 'includes maintenance_days when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('opt', required_attrs.merge(maintenance_days: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'opt')
        expect(config).to have_key('maintenance_days')
      end

      it 'omits maintenance_days when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'minimal')
        expect(config).not_to have_key('maintenance_days')
      end
      it 'includes monitor_guids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('opt', required_attrs.merge(monitor_guids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'opt')
        expect(config).to have_key('monitor_guids')
      end

      it 'omits monitor_guids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'minimal')
        expect(config).not_to have_key('monitor_guids')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_monitor_downtime', 'typed')
        expect(config['end_time']).to be_a(String)
        expect(config['mode']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['start_time']).to be_a(String)
        expect(config['time_zone']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_monitor_downtime('first', required_attrs)
        synth.newrelic_monitor_downtime('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_monitor_downtime')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_monitor_downtime,
    method: :newrelic_monitor_downtime,
    required_attrs: { end_time: 'test-value', mode: 'test-value', name: 'test-value', start_time: 'test-value', time_zone: 'test-value' },
    expected_outputs: [:id, :account_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
