# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_workload resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicWorkload do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':newrelic_workload' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_workload', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_workload('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_workload)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_workload('test', required_attrs)

        expect(ref.id).to eq("${newrelic_workload.test.id}")
        expect(ref.account_id).to eq("${newrelic_workload.test.account_id}")
        expect(ref.composite_entity_search_query).to eq("${newrelic_workload.test.composite_entity_search_query}")
        expect(ref.entity_guids).to eq("${newrelic_workload.test.entity_guids}")
        expect(ref.guid).to eq("${newrelic_workload.test.guid}")
        expect(ref.permalink).to eq("${newrelic_workload.test.permalink}")
        expect(ref.scope_account_ids).to eq("${newrelic_workload.test.scope_account_ids}")
        expect(ref.workload_id).to eq("${newrelic_workload.test.workload_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_workload', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('composite_entity_search_query')
        expect(config).not_to have_key('entity_guids')
        expect(config).not_to have_key('guid')
        expect(config).not_to have_key('permalink')
        expect(config).not_to have_key('scope_account_ids')
        expect(config).not_to have_key('workload_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', entity_search_query: [{ 'key1' => 'val1' }], status_config_automatic: [{ 'key1' => 'val1' }], status_config_static: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_workload', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('entity_search_query')
        expect(config).to have_key('status_config_automatic')
        expect(config).to have_key('status_config_static')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workload', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workload', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes entity_search_query when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('opt', required_attrs.merge(entity_search_query: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workload', 'opt')
        expect(config).to have_key('entity_search_query')
      end

      it 'omits entity_search_query when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workload', 'minimal')
        expect(config).not_to have_key('entity_search_query')
      end
      it 'includes status_config_automatic when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('opt', required_attrs.merge(status_config_automatic: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workload', 'opt')
        expect(config).to have_key('status_config_automatic')
      end

      it 'omits status_config_automatic when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workload', 'minimal')
        expect(config).not_to have_key('status_config_automatic')
      end
      it 'includes status_config_static when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('opt', required_attrs.merge(status_config_static: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workload', 'opt')
        expect(config).to have_key('status_config_static')
      end

      it 'omits status_config_static when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_workload', 'minimal')
        expect(config).not_to have_key('status_config_static')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_workload', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_workload('first', required_attrs)
        synth.newrelic_workload('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_workload')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_workload,
    method: :newrelic_workload,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :account_id, :composite_entity_search_query, :entity_guids, :guid, :permalink, :scope_account_ids, :workload_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
