# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_key_transaction resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicKeyTransaction do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { apdex_index: 3.14, application_guid: 'test-value', browser_apdex_target: 3.14, metric_name: 'test-value', name: 'test-value' } }

  describe ':newrelic_key_transaction' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_key_transaction('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_key_transaction', 'test')
        validate_required_attributes(config, [:apdex_index, :application_guid, :browser_apdex_target, :metric_name, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_key_transaction('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_key_transaction)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_key_transaction('test', required_attrs)

        expect(ref.id).to eq("${newrelic_key_transaction.test.id}")
        expect(ref.domain).to eq("${newrelic_key_transaction.test.domain}")
        expect(ref.type).to eq("${newrelic_key_transaction.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_key_transaction('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_key_transaction', 'test')
        expect(config).not_to have_key('domain')
        expect(config).not_to have_key('type')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_key_transaction('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_key_transaction', 'typed')
        expect(config['apdex_index']).to be_a(Float)
        expect(config['application_guid']).to be_a(String)
        expect(config['browser_apdex_target']).to be_a(Float)
        expect(config['metric_name']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_key_transaction('first', required_attrs)
        synth.newrelic_key_transaction('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_key_transaction')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_key_transaction,
    method: :newrelic_key_transaction,
    required_attrs: { apdex_index: 3.14, application_guid: 'test-value', browser_apdex_target: 3.14, metric_name: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :domain, :type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
