# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_browser_application resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicBrowserApplication do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':newrelic_browser_application' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_browser_application', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_browser_application('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_browser_application)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_browser_application('test', required_attrs)

        expect(ref.id).to eq("${newrelic_browser_application.test.id}")
        expect(ref.account_id).to eq("${newrelic_browser_application.test.account_id}")
        expect(ref.application_id).to eq("${newrelic_browser_application.test.application_id}")
        expect(ref.guid).to eq("${newrelic_browser_application.test.guid}")
        expect(ref.js_config).to eq("${newrelic_browser_application.test.js_config}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_browser_application', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('application_id')
        expect(config).not_to have_key('guid')
        expect(config).not_to have_key('js_config')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ cookies_enabled: true, distributed_tracing_enabled: true, loader_type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_browser_application', 'full')
        expect(config).to have_key('cookies_enabled')
        expect(config).to have_key('distributed_tracing_enabled')
        expect(config).to have_key('loader_type')
      end
    end

    context 'optional attributes' do
      it 'includes cookies_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('opt', required_attrs.merge(cookies_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_browser_application', 'opt')
        expect(config).to have_key('cookies_enabled')
      end

      it 'omits cookies_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_browser_application', 'minimal')
        expect(config).not_to have_key('cookies_enabled')
      end
      it 'includes distributed_tracing_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('opt', required_attrs.merge(distributed_tracing_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_browser_application', 'opt')
        expect(config).to have_key('distributed_tracing_enabled')
      end

      it 'omits distributed_tracing_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_browser_application', 'minimal')
        expect(config).not_to have_key('distributed_tracing_enabled')
      end
      it 'includes loader_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('opt', required_attrs.merge(loader_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_browser_application', 'opt')
        expect(config).to have_key('loader_type')
      end

      it 'omits loader_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_browser_application', 'minimal')
        expect(config).not_to have_key('loader_type')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts cookies_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(cookies_enabled: val)
          synth.newrelic_browser_application("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_browser_application', "bool_#{val}")
          expect(config['cookies_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts distributed_tracing_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(distributed_tracing_enabled: val)
          synth.newrelic_browser_application("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_browser_application', "bool_#{val}")
          expect(config['distributed_tracing_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_browser_application', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_browser_application('first', required_attrs)
        synth.newrelic_browser_application('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_browser_application')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_browser_application,
    method: :newrelic_browser_application,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :account_id, :application_id, :guid, :js_config],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:cookies_enabled, :distributed_tracing_enabled]
end
