# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_one_dashboard_raw resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicOneDashboardRaw do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', page: [{ 'key1' => 'val1' }] } }

  describe ':newrelic_one_dashboard_raw' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_raw('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_one_dashboard_raw', 'test')
        validate_required_attributes(config, [:name, :page])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_one_dashboard_raw('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_one_dashboard_raw)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_one_dashboard_raw('test', required_attrs)

        expect(ref.id).to eq("${newrelic_one_dashboard_raw.test.id}")
        expect(ref.account_id).to eq("${newrelic_one_dashboard_raw.test.account_id}")
        expect(ref.guid).to eq("${newrelic_one_dashboard_raw.test.guid}")
        expect(ref.permalink).to eq("${newrelic_one_dashboard_raw.test.permalink}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_raw('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_one_dashboard_raw', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('guid')
        expect(config).not_to have_key('permalink')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', permissions: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_raw('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_one_dashboard_raw', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('permissions')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_raw('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_one_dashboard_raw', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_one_dashboard_raw', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes permissions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_raw('opt', required_attrs.merge(permissions: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_one_dashboard_raw', 'opt')
        expect(config).to have_key('permissions')
      end

      it 'omits permissions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_one_dashboard_raw', 'minimal')
        expect(config).not_to have_key('permissions')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_raw('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_one_dashboard_raw', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['page']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_one_dashboard_raw('first', required_attrs)
        synth.newrelic_one_dashboard_raw('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_one_dashboard_raw')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_one_dashboard_raw,
    method: :newrelic_one_dashboard_raw,
    required_attrs: { name: 'test-value', page: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id, :account_id, :guid, :permalink],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
