# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_synthetics_multilocation_alert_condition resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicSyntheticsMultilocationAlertCondition do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { critical: [{ 'key1' => 'val1' }], entities: ['test-value'], name: 'test-value', policy_id: 3.14 } }

  describe ':newrelic_synthetics_multilocation_alert_condition' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'test')
        validate_required_attributes(config, [:critical, :entities, :name, :policy_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_multilocation_alert_condition('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_synthetics_multilocation_alert_condition)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_synthetics_multilocation_alert_condition('test', required_attrs)

        expect(ref.id).to eq("${newrelic_synthetics_multilocation_alert_condition.test.id}")
        expect(ref.entity_guid).to eq("${newrelic_synthetics_multilocation_alert_condition.test.entity_guid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'test')
        expect(config).not_to have_key('entity_guid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ enabled: true, runbook_url: 'test-value', violation_time_limit_seconds: 3.14, warning: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'full')
        expect(config).to have_key('enabled')
        expect(config).to have_key('runbook_url')
        expect(config).to have_key('violation_time_limit_seconds')
        expect(config).to have_key('warning')
      end
    end

    context 'optional attributes' do
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes runbook_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('opt', required_attrs.merge(runbook_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'opt')
        expect(config).to have_key('runbook_url')
      end

      it 'omits runbook_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'minimal')
        expect(config).not_to have_key('runbook_url')
      end
      it 'includes violation_time_limit_seconds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('opt', required_attrs.merge(violation_time_limit_seconds: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'opt')
        expect(config).to have_key('violation_time_limit_seconds')
      end

      it 'omits violation_time_limit_seconds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'minimal')
        expect(config).not_to have_key('violation_time_limit_seconds')
      end
      it 'includes warning when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('opt', required_attrs.merge(warning: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'opt')
        expect(config).to have_key('warning')
      end

      it 'omits warning when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'minimal')
        expect(config).not_to have_key('warning')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.newrelic_synthetics_multilocation_alert_condition("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_synthetics_multilocation_alert_condition', 'typed')
        expect(config['critical']).to be_a(Array)
        expect(config['entities']).to be_a(Array)
        expect(config['name']).to be_a(String)
        expect(config['policy_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_synthetics_multilocation_alert_condition('first', required_attrs)
        synth.newrelic_synthetics_multilocation_alert_condition('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_synthetics_multilocation_alert_condition')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_synthetics_multilocation_alert_condition,
    method: :newrelic_synthetics_multilocation_alert_condition,
    required_attrs: { critical: [{ 'key1' => 'val1' }], entities: ['test-value'], name: 'test-value', policy_id: 3.14 },
    expected_outputs: [:id, :entity_guid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
