# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_cloud_gcp_integrations resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicCloudGcpIntegrations do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { linked_account_id: 3.14 } }

  describe ':newrelic_cloud_gcp_integrations' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'test')
        validate_required_attributes(config, [:linked_account_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_cloud_gcp_integrations('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_cloud_gcp_integrations)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_cloud_gcp_integrations('test', required_attrs)

        expect(ref.id).to eq("${newrelic_cloud_gcp_integrations.test.id}")
        expect(ref.account_id).to eq("${newrelic_cloud_gcp_integrations.test.account_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'test')
        expect(config).not_to have_key('account_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alloy_db: [{ 'key1' => 'val1' }], app_engine: [{ 'key1' => 'val1' }], big_query: [{ 'key1' => 'val1' }], big_table: [{ 'key1' => 'val1' }], composer: [{ 'key1' => 'val1' }], data_flow: [{ 'key1' => 'val1' }], data_proc: [{ 'key1' => 'val1' }], data_store: [{ 'key1' => 'val1' }], fire_base_database: [{ 'key1' => 'val1' }], fire_base_hosting: [{ 'key1' => 'val1' }], fire_base_storage: [{ 'key1' => 'val1' }], fire_store: [{ 'key1' => 'val1' }], functions: [{ 'key1' => 'val1' }], interconnect: [{ 'key1' => 'val1' }], kubernetes: [{ 'key1' => 'val1' }], load_balancing: [{ 'key1' => 'val1' }], mem_cache: [{ 'key1' => 'val1' }], pub_sub: [{ 'key1' => 'val1' }], redis: [{ 'key1' => 'val1' }], router: [{ 'key1' => 'val1' }], run: [{ 'key1' => 'val1' }], spanner: [{ 'key1' => 'val1' }], sql: [{ 'key1' => 'val1' }], storage: [{ 'key1' => 'val1' }], virtual_machines: [{ 'key1' => 'val1' }], vpc_access: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'full')
        expect(config).to have_key('alloy_db')
        expect(config).to have_key('app_engine')
        expect(config).to have_key('big_query')
        expect(config).to have_key('big_table')
        expect(config).to have_key('composer')
        expect(config).to have_key('data_flow')
        expect(config).to have_key('data_proc')
        expect(config).to have_key('data_store')
        expect(config).to have_key('fire_base_database')
        expect(config).to have_key('fire_base_hosting')
        expect(config).to have_key('fire_base_storage')
        expect(config).to have_key('fire_store')
        expect(config).to have_key('functions')
        expect(config).to have_key('interconnect')
        expect(config).to have_key('kubernetes')
        expect(config).to have_key('load_balancing')
        expect(config).to have_key('mem_cache')
        expect(config).to have_key('pub_sub')
        expect(config).to have_key('redis')
        expect(config).to have_key('router')
        expect(config).to have_key('run')
        expect(config).to have_key('spanner')
        expect(config).to have_key('sql')
        expect(config).to have_key('storage')
        expect(config).to have_key('virtual_machines')
        expect(config).to have_key('vpc_access')
      end
    end

    context 'optional attributes' do
      it 'includes alloy_db when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(alloy_db: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('alloy_db')
      end

      it 'omits alloy_db when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('alloy_db')
      end
      it 'includes app_engine when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(app_engine: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('app_engine')
      end

      it 'omits app_engine when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('app_engine')
      end
      it 'includes big_query when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(big_query: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('big_query')
      end

      it 'omits big_query when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('big_query')
      end
      it 'includes big_table when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(big_table: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('big_table')
      end

      it 'omits big_table when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('big_table')
      end
      it 'includes composer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(composer: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('composer')
      end

      it 'omits composer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('composer')
      end
      it 'includes data_flow when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(data_flow: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('data_flow')
      end

      it 'omits data_flow when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('data_flow')
      end
      it 'includes data_proc when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(data_proc: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('data_proc')
      end

      it 'omits data_proc when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('data_proc')
      end
      it 'includes data_store when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(data_store: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('data_store')
      end

      it 'omits data_store when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('data_store')
      end
      it 'includes fire_base_database when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(fire_base_database: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('fire_base_database')
      end

      it 'omits fire_base_database when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('fire_base_database')
      end
      it 'includes fire_base_hosting when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(fire_base_hosting: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('fire_base_hosting')
      end

      it 'omits fire_base_hosting when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('fire_base_hosting')
      end
      it 'includes fire_base_storage when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(fire_base_storage: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('fire_base_storage')
      end

      it 'omits fire_base_storage when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('fire_base_storage')
      end
      it 'includes fire_store when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(fire_store: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('fire_store')
      end

      it 'omits fire_store when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('fire_store')
      end
      it 'includes functions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(functions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('functions')
      end

      it 'omits functions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('functions')
      end
      it 'includes interconnect when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(interconnect: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('interconnect')
      end

      it 'omits interconnect when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('interconnect')
      end
      it 'includes kubernetes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(kubernetes: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('kubernetes')
      end

      it 'omits kubernetes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('kubernetes')
      end
      it 'includes load_balancing when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(load_balancing: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('load_balancing')
      end

      it 'omits load_balancing when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('load_balancing')
      end
      it 'includes mem_cache when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(mem_cache: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('mem_cache')
      end

      it 'omits mem_cache when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('mem_cache')
      end
      it 'includes pub_sub when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(pub_sub: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('pub_sub')
      end

      it 'omits pub_sub when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('pub_sub')
      end
      it 'includes redis when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(redis: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('redis')
      end

      it 'omits redis when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('redis')
      end
      it 'includes router when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(router: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('router')
      end

      it 'omits router when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('router')
      end
      it 'includes run when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(run: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('run')
      end

      it 'omits run when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('run')
      end
      it 'includes spanner when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(spanner: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('spanner')
      end

      it 'omits spanner when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('spanner')
      end
      it 'includes sql when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(sql: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('sql')
      end

      it 'omits sql when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('sql')
      end
      it 'includes storage when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(storage: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('storage')
      end

      it 'omits storage when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('storage')
      end
      it 'includes virtual_machines when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(virtual_machines: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('virtual_machines')
      end

      it 'omits virtual_machines when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('virtual_machines')
      end
      it 'includes vpc_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('opt', required_attrs.merge(vpc_access: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'opt')
        expect(config).to have_key('vpc_access')
      end

      it 'omits vpc_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'minimal')
        expect(config).not_to have_key('vpc_access')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_cloud_gcp_integrations', 'typed')
        expect(config['linked_account_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_cloud_gcp_integrations('first', required_attrs)
        synth.newrelic_cloud_gcp_integrations('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_cloud_gcp_integrations')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_cloud_gcp_integrations,
    method: :newrelic_cloud_gcp_integrations,
    required_attrs: { linked_account_id: 3.14 },
    expected_outputs: [:id, :account_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
