# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_alert_compound_condition resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicAlertCompoundCondition do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { component_conditions: [{ 'key1' => 'val1' }], enabled: true, name: 'test-value', policy_id: 3.14, trigger_expression: 'test-value' } }

  describe ':newrelic_alert_compound_condition' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_alert_compound_condition('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_alert_compound_condition', 'test')
        validate_required_attributes(config, [:component_conditions, :enabled, :name, :policy_id, :trigger_expression])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_alert_compound_condition('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_alert_compound_condition)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_alert_compound_condition('test', required_attrs)

        expect(ref.id).to eq("${newrelic_alert_compound_condition.test.id}")
        expect(ref.account_id).to eq("${newrelic_alert_compound_condition.test.account_id}")
        expect(ref.facet_matching_behavior).to eq("${newrelic_alert_compound_condition.test.facet_matching_behavior}")
        expect(ref.threshold_duration).to eq("${newrelic_alert_compound_condition.test.threshold_duration}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_alert_compound_condition('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_alert_compound_condition', 'test')
        expect(config).not_to have_key('account_id')
        expect(config).not_to have_key('facet_matching_behavior')
        expect(config).not_to have_key('threshold_duration')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ runbook_url: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_alert_compound_condition('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_alert_compound_condition', 'full')
        expect(config).to have_key('runbook_url')
      end
    end

    context 'optional attributes' do
      it 'includes runbook_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_alert_compound_condition('opt', required_attrs.merge(runbook_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_alert_compound_condition', 'opt')
        expect(config).to have_key('runbook_url')
      end

      it 'omits runbook_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_alert_compound_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_alert_compound_condition', 'minimal')
        expect(config).not_to have_key('runbook_url')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.newrelic_alert_compound_condition("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_alert_compound_condition', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_alert_compound_condition('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_alert_compound_condition', 'typed')
        expect(config['component_conditions']).to be_a(Array)
        expect([true, false]).to include(config['enabled'])
        expect(config['name']).to be_a(String)
        expect(config['policy_id']).to be_a(Float)
        expect(config['trigger_expression']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_alert_compound_condition('first', required_attrs)
        synth.newrelic_alert_compound_condition('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_alert_compound_condition')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_alert_compound_condition,
    method: :newrelic_alert_compound_condition,
    required_attrs: { component_conditions: [{ 'key1' => 'val1' }], enabled: true, name: 'test-value', policy_id: 3.14, trigger_expression: 'test-value' },
    expected_outputs: [:id, :account_id, :facet_matching_behavior, :threshold_duration],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
