# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a newrelic_infra_alert_condition resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::NewrelicInfraAlertCondition do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', policy_id: 3.14, type: 'test-value' } }

  describe ':newrelic_infra_alert_condition' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'test')
        validate_required_attributes(config, [:name, :policy_id, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_infra_alert_condition('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:newrelic_infra_alert_condition)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.newrelic_infra_alert_condition('test', required_attrs)

        expect(ref.id).to eq("${newrelic_infra_alert_condition.test.id}")
        expect(ref.created_at).to eq("${newrelic_infra_alert_condition.test.created_at}")
        expect(ref.entity_guid).to eq("${newrelic_infra_alert_condition.test.entity_guid}")
        expect(ref.event).to eq("${newrelic_infra_alert_condition.test.event}")
        expect(ref.updated_at).to eq("${newrelic_infra_alert_condition.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('entity_guid')
        expect(config).not_to have_key('event')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comparison: 'test-value', critical: [{ 'key1' => 'val1' }], description: 'test-value', enabled: true, integration_provider: 'test-value', process_where: 'test-value', runbook_url: 'test-value', select: 'test-value', violation_close_timer: 3.14, warning: [{ 'key1' => 'val1' }], where: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'full')
        expect(config).to have_key('comparison')
        expect(config).to have_key('critical')
        expect(config).to have_key('description')
        expect(config).to have_key('enabled')
        expect(config).to have_key('integration_provider')
        expect(config).to have_key('process_where')
        expect(config).to have_key('runbook_url')
        expect(config).to have_key('select')
        expect(config).to have_key('violation_close_timer')
        expect(config).to have_key('warning')
        expect(config).to have_key('where')
      end
    end

    context 'optional attributes' do
      it 'includes comparison when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(comparison: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('comparison')
      end

      it 'omits comparison when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('comparison')
      end
      it 'includes critical when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(critical: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('critical')
      end

      it 'omits critical when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('critical')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes integration_provider when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(integration_provider: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('integration_provider')
      end

      it 'omits integration_provider when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('integration_provider')
      end
      it 'includes process_where when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(process_where: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('process_where')
      end

      it 'omits process_where when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('process_where')
      end
      it 'includes runbook_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(runbook_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('runbook_url')
      end

      it 'omits runbook_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('runbook_url')
      end
      it 'includes select when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(select: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('select')
      end

      it 'omits select when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('select')
      end
      it 'includes violation_close_timer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(violation_close_timer: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('violation_close_timer')
      end

      it 'omits violation_close_timer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('violation_close_timer')
      end
      it 'includes warning when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(warning: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('warning')
      end

      it 'omits warning when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('warning')
      end
      it 'includes where when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('opt', required_attrs.merge(where: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'opt')
        expect(config).to have_key('where')
      end

      it 'omits where when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'minimal')
        expect(config).not_to have_key('where')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.newrelic_infra_alert_condition("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'newrelic_infra_alert_condition', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'newrelic_infra_alert_condition', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['policy_id']).to be_a(Float)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.newrelic_infra_alert_condition('first', required_attrs)
        synth.newrelic_infra_alert_condition('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'newrelic_infra_alert_condition')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :newrelic_infra_alert_condition,
    method: :newrelic_infra_alert_condition,
    required_attrs: { name: 'test-value', policy_id: 3.14, type: 'test-value' },
    expected_outputs: [:id, :created_at, :entity_guid, :event, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
